// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: lua.flex

package com.nirithy.lxclua;

import static com.nirithy.lxclua.LuaTokenTypes.*;
import java.io.IOException;
import java.io.Reader;


@SuppressWarnings("fallthrough")
public class LuaLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int xSHEBANG = 2;
  public static final int xDOUBLE_QUOTED_STRING = 4;
  public static final int xSINGLE_QUOTED_STRING = 6;
  public static final int xBLOCK_STRING = 8;
  public static final int xBLOCK_COMMENT = 10;
  public static final int xREGEX = 12;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\10\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\2\37\1\41\1\37\11\42\1\43"+
    "\7\42\1\44\2\42\1\45\1\46\1\47\1\50\1\51"+
    "\1\0\1\52\1\53\1\54\1\55\1\56\1\57\1\60"+
    "\1\61\1\62\1\42\1\63\1\64\1\65\1\66\1\67"+
    "\1\70\1\71\1\72\1\73\1\74\1\75\1\76\1\77"+
    "\1\100\1\101\1\42\1\102\1\103\1\104\1\105\6\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\1\2\2\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\2\23\1\24\1\25\1\26\1\27"+
    "\1\30\1\31\1\32\1\33\1\34\1\35\1\36\25\33"+
    "\1\37\1\40\1\41\1\42\1\43\2\44\1\43\2\45"+
    "\1\46\1\0\1\43\2\45\1\0\3\47\1\50\1\0"+
    "\1\51\1\0\1\52\1\0\1\53\1\0\1\54\1\55"+
    "\1\56\2\0\1\57\1\60\1\61\1\62\1\63\1\64"+
    "\1\65\1\0\1\66\1\67\1\23\4\0\1\70\1\71"+
    "\1\72\1\73\1\74\1\75\1\76\1\77\1\100\1\101"+
    "\1\102\1\103\1\0\1\104\1\105\3\33\1\106\10\33"+
    "\1\107\13\33\1\110\1\33\1\111\1\112\12\33\1\113"+
    "\16\33\1\114\1\115\3\0\1\43\2\0\1\43\1\0"+
    "\1\116\1\0\1\117\1\120\2\0\1\62\1\121\3\62"+
    "\1\122\1\123\1\124\1\125\1\23\1\0\2\23\1\126"+
    "\1\127\1\130\1\131\2\33\1\55\1\132\16\33\1\133"+
    "\6\33\1\134\6\33\1\135\2\33\1\136\4\33\1\137"+
    "\1\140\1\4\16\33\1\141\6\33\1\142\1\143\2\62"+
    "\1\23\4\33\1\144\1\33\1\145\1\33\1\146\11\33"+
    "\1\147\1\150\7\33\1\151\7\33\1\152\15\33\1\153"+
    "\1\154\1\155\2\33\1\156\1\157\1\33\1\160\2\62"+
    "\3\0\1\33\1\161\1\162\1\163\1\164\1\165\2\33"+
    "\1\166\2\33\1\167\5\33\1\170\1\171\1\172\2\33"+
    "\1\173\5\33\1\174\1\175\12\33\1\176\1\33\1\177"+
    "\1\200\1\201\2\62\1\202\1\203\5\33\1\204\1\205"+
    "\1\206\1\207\3\33\1\210\4\33\1\211\4\33\1\212"+
    "\1\213\1\33\1\214\1\215\1\216\1\33\1\217\2\62"+
    "\1\33\1\220\1\221\1\33\1\222\1\223\1\224\4\33"+
    "\1\225\2\33\1\226\3\33\1\62\1\227\1\230\1\231"+
    "\1\232\4\33\1\233\1\33\1\234\1\33\1\62\2\33"+
    "\1\235\1\236\1\237\1\33\1\62\1\240\1\241\1\33"+
    "\1\242\1\243";

  private static int [] zzUnpackAction() {
    int [] result = new int[465];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\106\0\214\0\322\0\u0118\0\u015e\0\u01a4\0\u01a4"+
    "\0\u01ea\0\u01a4\0\u0230\0\u0276\0\u02bc\0\u0302\0\u0348\0\u038e"+
    "\0\u03d4\0\u041a\0\u01a4\0\u01a4\0\u0460\0\u04a6\0\u01a4\0\u04ec"+
    "\0\u0532\0\u0578\0\u05be\0\u0604\0\u064a\0\u01a4\0\u0690\0\u06d6"+
    "\0\u071c\0\u0762\0\u01a4\0\u07a8\0\u07ee\0\u01a4\0\u0834\0\u087a"+
    "\0\u08c0\0\u0906\0\u094c\0\u0992\0\u09d8\0\u0a1e\0\u0a64\0\u0aaa"+
    "\0\u0af0\0\u0b36\0\u0b7c\0\u0bc2\0\u0c08\0\u0c4e\0\u0c94\0\u0cda"+
    "\0\u0d20\0\u0d66\0\u0dac\0\u0df2\0\u01a4\0\u0e38\0\u01a4\0\u0276"+
    "\0\u0e7e\0\u01a4\0\u0ec4\0\u0f0a\0\u0f50\0\u0f96\0\u01a4\0\u0fdc"+
    "\0\u1022\0\u1068\0\u10ae\0\u10f4\0\u113a\0\u1180\0\u11c6\0\u01a4"+
    "\0\u02bc\0\u01a4\0\u120c\0\u01a4\0\u1252\0\u01a4\0\u1298\0\u01a4"+
    "\0\u01a4\0\u01a4\0\u041a\0\u12de\0\u01a4\0\u01a4\0\u01a4\0\u1324"+
    "\0\u01a4\0\u01a4\0\u136a\0\u13b0\0\u13f6\0\u01a4\0\u143c\0\u1482"+
    "\0\u14c8\0\u150e\0\u1554\0\u01a4\0\u01a4\0\u159a\0\u15e0\0\u01a4"+
    "\0\u01a4\0\u01a4\0\u01a4\0\u01a4\0\u1626\0\u01a4\0\u166c\0\u07ee"+
    "\0\u01a4\0\u01a4\0\u16b2\0\u16f8\0\u173e\0\u1784\0\u17ca\0\u1810"+
    "\0\u1856\0\u189c\0\u18e2\0\u1928\0\u196e\0\u19b4\0\u19fa\0\u1a40"+
    "\0\u1a86\0\u1acc\0\u1b12\0\u1b58\0\u1b9e\0\u1be4\0\u1c2a\0\u1c70"+
    "\0\u1cb6\0\u1cfc\0\u07a8\0\u1d42\0\u1d88\0\u07a8\0\u1dce\0\u1e14"+
    "\0\u1e5a\0\u1ea0\0\u1ee6\0\u1f2c\0\u1f72\0\u1fb8\0\u1ffe\0\u2044"+
    "\0\u07a8\0\u208a\0\u20d0\0\u2116\0\u215c\0\u21a2\0\u21e8\0\u222e"+
    "\0\u2274\0\u22ba\0\u2300\0\u2346\0\u238c\0\u23d2\0\u2418\0\u01a4"+
    "\0\u01a4\0\u245e\0\u0f50\0\u24a4\0\u0f50\0\u1068\0\u24ea\0\u1068"+
    "\0\u1180\0\u01a4\0\u11c6\0\u01a4\0\u01a4\0\u2530\0\u2576\0\u25bc"+
    "\0\u2602\0\u2648\0\u268e\0\u26d4\0\u01a4\0\u01a4\0\u271a\0\u01a4"+
    "\0\u2760\0\u27a6\0\u27ec\0\u2832\0\u01a4\0\u01a4\0\u01a4\0\u01a4"+
    "\0\u2878\0\u28be\0\u07a8\0\u07a8\0\u2904\0\u294a\0\u2990\0\u29d6"+
    "\0\u2a1c\0\u2a62\0\u2aa8\0\u2aee\0\u2b34\0\u2b7a\0\u2bc0\0\u2c06"+
    "\0\u2c4c\0\u2c92\0\u07a8\0\u2cd8\0\u2d1e\0\u2d64\0\u2daa\0\u2df0"+
    "\0\u2e36\0\u07a8\0\u2e7c\0\u2ec2\0\u2f08\0\u2f4e\0\u2f94\0\u2fda"+
    "\0\u3020\0\u3066\0\u30ac\0\u07a8\0\u30f2\0\u3138\0\u317e\0\u31c4"+
    "\0\u07a8\0\u07a8\0\u07a8\0\u320a\0\u3250\0\u3296\0\u32dc\0\u3322"+
    "\0\u3368\0\u33ae\0\u33f4\0\u343a\0\u3480\0\u34c6\0\u350c\0\u3552"+
    "\0\u3598\0\u07a8\0\u35de\0\u3624\0\u366a\0\u36b0\0\u36f6\0\u373c"+
    "\0\u01a4\0\u25bc\0\u3782\0\u37c8\0\u380e\0\u3854\0\u389a\0\u38e0"+
    "\0\u3926\0\u07a8\0\u396c\0\u07a8\0\u39b2\0\u07a8\0\u39f8\0\u3a3e"+
    "\0\u3a84\0\u3aca\0\u3b10\0\u3b56\0\u3b9c\0\u3be2\0\u3c28\0\u3c6e"+
    "\0\u07a8\0\u3cb4\0\u3cfa\0\u3d40\0\u3d86\0\u3dcc\0\u3e12\0\u3e58"+
    "\0\u07a8\0\u3e9e\0\u3ee4\0\u3f2a\0\u3f70\0\u3fb6\0\u3ffc\0\u4042"+
    "\0\u07a8\0\u4088\0\u40ce\0\u4114\0\u415a\0\u41a0\0\u41e6\0\u422c"+
    "\0\u4272\0\u42b8\0\u42fe\0\u4344\0\u438a\0\u43d0\0\u07a8\0\u07a8"+
    "\0\u07a8\0\u4416\0\u445c\0\u07a8\0\u07a8\0\u44a2\0\u07a8\0\u44e8"+
    "\0\u452e\0\u4574\0\u45ba\0\u4600\0\u4646\0\u07a8\0\u07a8\0\u07a8"+
    "\0\u07a8\0\u07a8\0\u468c\0\u46d2\0\u07a8\0\u4718\0\u475e\0\u07a8"+
    "\0\u47a4\0\u47ea\0\u4830\0\u4876\0\u48bc\0\u07a8\0\u4902\0\u07a8"+
    "\0\u4948\0\u498e\0\u07a8\0\u49d4\0\u4a1a\0\u4a60\0\u4aa6\0\u4aec"+
    "\0\u07a8\0\u07a8\0\u4b32\0\u4b78\0\u4bbe\0\u4c04\0\u4c4a\0\u4c90"+
    "\0\u4cd6\0\u4d1c\0\u4d62\0\u4da8\0\u4dee\0\u4e34\0\u07a8\0\u07a8"+
    "\0\u07a8\0\u4e7a\0\u4ec0\0\u01a4\0\u01a4\0\u4f06\0\u4f4c\0\u4f92"+
    "\0\u4fd8\0\u501e\0\u07a8\0\u07a8\0\u07a8\0\u07a8\0\u5064\0\u50aa"+
    "\0\u50f0\0\u07a8\0\u5136\0\u517c\0\u51c2\0\u5208\0\u07a8\0\u524e"+
    "\0\u5294\0\u52da\0\u5320\0\u07a8\0\u07a8\0\u5366\0\u07a8\0\u07a8"+
    "\0\u07a8\0\u53ac\0\u07a8\0\u53f2\0\u5438\0\u547e\0\u07a8\0\u07a8"+
    "\0\u54c4\0\u07a8\0\u07a8\0\u07a8\0\u550a\0\u5550\0\u5596\0\u55dc"+
    "\0\u07a8\0\u5622\0\u5668\0\u07a8\0\u56ae\0\u56f4\0\u573a\0\u5780"+
    "\0\u57c6\0\u07a8\0\u07a8\0\u07a8\0\u580c\0\u5852\0\u5898\0\u58de"+
    "\0\u07a8\0\u5924\0\u07a8\0\u596a\0\u59b0\0\u59f6\0\u5a3c\0\u07a8"+
    "\0\u07a8\0\u07a8\0\u5a82\0\u5ac8\0\u07a8\0\u07a8\0\u5b0e\0\u5b54"+
    "\0\u07a8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[465];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\1\12\1\0\1\11\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\2\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\6\44\1\45"+
    "\1\10\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\1\55\1\56\1\57\1\44\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\44\1\67\1\70\1\71\1\72"+
    "\1\73\1\74\2\44\1\75\1\76\1\77\1\100\2\101"+
    "\1\102\2\101\1\103\100\101\2\104\1\105\2\104\1\106"+
    "\1\104\1\107\36\104\1\110\37\104\2\111\1\112\2\111"+
    "\1\113\6\111\1\107\31\111\1\114\37\111\47\115\1\116"+
    "\105\115\1\117\36\115\107\0\1\11\2\0\1\11\103\0"+
    "\1\12\136\0\1\120\52\0\7\121\1\122\36\121\1\123"+
    "\37\121\6\0\1\124\106\0\1\125\1\0\1\126\2\0"+
    "\1\127\124\0\1\130\65\0\1\131\17\0\1\132\52\0"+
    "\14\133\1\122\31\133\1\134\37\133\33\0\1\135\72\0"+
    "\1\136\12\0\1\137\74\0\1\140\10\0\1\141\1\142"+
    "\74\0\1\143\62\0\1\144\2\0\1\144\3\0\1\144"+
    "\4\0\1\144\7\0\1\145\6\0\1\146\3\0\6\144"+
    "\1\0\1\144\2\0\31\144\27\0\1\147\1\0\3\34"+
    "\10\0\1\150\1\151\2\0\1\152\4\0\1\153\1\0"+
    "\1\150\2\0\1\151\21\0\1\152\30\0\1\147\1\0"+
    "\3\34\11\0\1\151\7\0\1\153\4\0\1\151\57\0"+
    "\1\154\2\0\1\155\104\0\1\156\1\157\1\160\46\0"+
    "\1\161\35\0\1\162\1\163\104\0\1\164\1\165\74\0"+
    "\1\166\11\0\1\167\75\0\3\44\7\0\6\44\4\0"+
    "\31\44\37\0\1\170\11\0\1\171\73\0\1\172\77\0"+
    "\3\44\7\0\6\44\4\0\21\44\1\173\7\44\31\0"+
    "\3\44\7\0\6\44\4\0\2\44\1\174\12\44\1\175"+
    "\4\44\1\176\3\44\1\177\2\44\31\0\3\44\7\0"+
    "\6\44\4\0\16\44\1\200\2\44\1\201\7\44\31\0"+
    "\3\44\7\0\6\44\4\0\1\44\1\202\6\44\1\203"+
    "\2\44\1\204\2\44\1\205\12\44\31\0\3\44\7\0"+
    "\6\44\4\0\5\44\1\206\10\44\1\207\12\44\31\0"+
    "\3\44\7\0\6\44\4\0\13\44\1\210\1\44\1\211"+
    "\11\44\1\212\1\44\13\0\1\125\4\0\1\127\10\0"+
    "\3\44\7\0\6\44\4\0\1\44\1\213\7\44\1\214"+
    "\1\44\1\215\2\44\1\216\5\44\1\217\4\44\31\0"+
    "\3\44\7\0\6\44\4\0\13\44\1\220\2\44\1\221"+
    "\5\44\1\222\4\44\31\0\3\44\7\0\6\44\4\0"+
    "\6\44\1\223\5\44\1\224\1\225\4\44\1\226\6\44"+
    "\31\0\3\44\7\0\6\44\4\0\5\44\1\227\23\44"+
    "\31\0\3\44\7\0\6\44\4\0\1\44\1\230\3\44"+
    "\1\231\10\44\1\232\12\44\31\0\3\44\7\0\6\44"+
    "\4\0\1\44\1\233\27\44\31\0\3\44\7\0\6\44"+
    "\4\0\1\44\1\234\3\44\1\235\3\44\1\236\4\44"+
    "\1\237\12\44\31\0\3\44\7\0\6\44\4\0\17\44"+
    "\1\240\1\44\1\241\7\44\31\0\3\44\7\0\6\44"+
    "\4\0\21\44\1\242\2\44\1\243\4\44\31\0\3\44"+
    "\7\0\6\44\4\0\5\44\1\244\23\44\31\0\3\44"+
    "\7\0\6\44\4\0\23\44\1\245\1\246\1\44\1\247"+
    "\2\44\31\0\3\44\7\0\6\44\4\0\1\44\1\250"+
    "\6\44\1\251\10\44\1\252\7\44\31\0\3\44\7\0"+
    "\6\44\4\0\15\44\1\253\4\44\1\254\6\44\31\0"+
    "\3\44\7\0\6\44\4\0\16\44\1\255\12\44\31\0"+
    "\3\44\7\0\6\44\4\0\10\44\1\256\1\257\17\44"+
    "\37\0\1\260\1\261\1\262\50\0\2\101\1\0\2\101"+
    "\1\0\100\101\2\0\1\102\103\0\2\104\1\263\2\104"+
    "\1\263\1\104\1\107\36\104\1\264\37\104\7\263\1\107"+
    "\36\263\1\264\41\263\1\105\4\263\1\107\36\263\1\264"+
    "\37\263\2\265\4\263\100\265\2\111\1\266\2\111\1\266"+
    "\6\111\1\107\31\111\1\267\37\111\14\266\1\107\31\266"+
    "\1\267\41\266\1\112\11\266\1\107\31\266\1\267\37\266"+
    "\2\270\4\266\100\270\47\115\1\0\36\115\33\0\1\271"+
    "\13\0\1\272\71\0\1\273\13\0\1\274\36\0\106\121"+
    "\7\125\1\275\36\125\1\276\37\125\14\127\1\275\31\127"+
    "\1\277\37\127\106\133\2\300\1\0\2\300\1\0\14\300"+
    "\1\301\22\300\1\302\10\300\1\303\13\300\1\304\13\300"+
    "\23\0\1\305\7\0\1\306\52\0\2\144\1\0\2\144"+
    "\1\0\16\144\1\307\61\144\33\0\1\310\77\0\3\147"+
    "\11\0\1\151\14\0\1\151\54\0\2\311\77\0\1\312"+
    "\1\0\1\312\2\0\3\313\103\0\3\314\7\0\3\314"+
    "\10\0\6\314\53\0\3\34\111\0\1\315\106\0\1\316"+
    "\104\0\1\317\105\0\1\320\77\0\3\44\7\0\6\44"+
    "\4\0\1\44\1\321\27\44\31\0\3\44\7\0\6\44"+
    "\4\0\22\44\1\322\6\44\31\0\3\44\7\0\6\44"+
    "\4\0\4\44\1\323\24\44\31\0\3\44\7\0\6\44"+
    "\4\0\14\44\1\324\13\44\1\325\31\0\3\44\7\0"+
    "\6\44\4\0\1\44\1\326\27\44\31\0\3\44\7\0"+
    "\6\44\4\0\16\44\1\327\12\44\31\0\3\44\7\0"+
    "\6\44\4\0\5\44\1\330\23\44\31\0\3\44\7\0"+
    "\6\44\4\0\22\44\1\331\1\332\5\44\31\0\3\44"+
    "\7\0\6\44\4\0\1\44\1\333\27\44\31\0\3\44"+
    "\7\0\6\44\4\0\1\44\1\334\27\44\31\0\3\44"+
    "\7\0\6\44\4\0\14\44\1\335\1\336\13\44\31\0"+
    "\3\44\7\0\6\44\4\0\6\44\1\337\4\44\1\340"+
    "\15\44\31\0\3\44\7\0\6\44\4\0\24\44\1\341"+
    "\4\44\31\0\3\44\7\0\6\44\4\0\22\44\1\342"+
    "\6\44\31\0\3\44\7\0\6\44\4\0\4\44\1\343"+
    "\17\44\1\344\4\44\31\0\3\44\7\0\6\44\4\0"+
    "\17\44\1\345\3\44\1\346\5\44\31\0\3\44\7\0"+
    "\6\44\4\0\13\44\1\347\15\44\31\0\3\44\7\0"+
    "\6\44\4\0\15\44\1\350\13\44\31\0\3\44\7\0"+
    "\6\44\4\0\16\44\1\351\12\44\31\0\3\44\7\0"+
    "\6\44\4\0\21\44\1\352\7\44\31\0\3\44\7\0"+
    "\6\44\4\0\15\44\1\353\13\44\31\0\3\44\7\0"+
    "\6\44\4\0\16\44\1\354\12\44\31\0\3\44\7\0"+
    "\6\44\4\0\23\44\1\355\5\44\31\0\3\44\7\0"+
    "\6\44\4\0\1\44\1\356\27\44\31\0\3\44\7\0"+
    "\6\44\4\0\17\44\1\357\11\44\31\0\3\44\7\0"+
    "\6\44\4\0\22\44\1\360\1\361\5\44\31\0\3\44"+
    "\7\0\6\44\4\0\30\44\1\362\31\0\3\44\7\0"+
    "\6\44\4\0\14\44\1\363\14\44\31\0\3\44\7\0"+
    "\6\44\4\0\23\44\1\364\5\44\31\0\3\44\7\0"+
    "\6\44\4\0\3\44\1\365\11\44\1\366\13\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\367\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\14\44\1\370\14\44\31\0"+
    "\3\44\7\0\6\44\4\0\26\44\1\371\2\44\31\0"+
    "\3\44\7\0\6\44\4\0\13\44\1\372\15\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\373\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\374\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\11\44\1\375\4\44\1\376"+
    "\12\44\31\0\3\44\7\0\6\44\4\0\2\44\1\377"+
    "\26\44\31\0\3\44\7\0\6\44\4\0\17\44\1\u0100"+
    "\1\u0101\2\44\1\u0102\5\44\31\0\3\44\7\0\6\44"+
    "\4\0\1\44\1\u0103\17\44\1\u0104\7\44\31\0\3\44"+
    "\7\0\6\44\4\0\17\44\1\u0105\11\44\31\0\3\44"+
    "\7\0\6\44\4\0\11\44\1\u0106\17\44\31\0\3\44"+
    "\7\0\6\44\4\0\12\44\1\u0107\16\44\31\0\3\44"+
    "\7\0\6\44\4\0\5\44\1\u0108\23\44\31\0\3\44"+
    "\7\0\6\44\4\0\24\44\1\u0109\3\44\1\u010a\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\u010b\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\11\44\1\u010c\17\44\31\0"+
    "\3\44\7\0\6\44\4\0\11\44\1\u010d\17\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u010e\3\44\1\u010f"+
    "\17\44\31\0\3\44\7\0\6\44\4\0\23\44\1\u0110"+
    "\5\44\40\0\1\u0111\51\0\106\263\106\266\106\125\106\127"+
    "\2\300\1\0\2\300\1\0\100\300\2\301\1\0\2\301"+
    "\1\0\100\301\2\300\1\0\2\300\1\0\25\300\1\302"+
    "\11\300\1\u0112\42\300\1\0\2\300\1\0\60\300\1\u0113"+
    "\21\300\1\0\2\300\1\0\50\300\1\u0114\27\300\37\0"+
    "\6\307\5\0\30\307\31\0\2\311\22\0\1\150\61\0"+
    "\3\313\103\0\3\313\21\0\1\312\57\0\1\u0115\1\0"+
    "\3\314\7\0\3\314\1\0\1\151\5\0\1\152\6\314"+
    "\10\0\1\151\42\0\3\44\7\0\6\44\4\0\26\44"+
    "\1\u0116\2\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u0117\5\44\31\0\3\44\7\0\6\44\4\0\15\44"+
    "\1\u0118\13\44\31\0\3\44\7\0\6\44\4\0\11\44"+
    "\1\u0119\17\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u011a\15\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u011b\27\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u011c\23\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u011d\25\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u011e\7\44\31\0\3\44\7\0\6\44\4\0\22\44"+
    "\1\u011f\6\44\31\0\3\44\7\0\6\44\4\0\14\44"+
    "\1\u0120\14\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u0121\16\44\1\u0122\1\u0123\5\44\31\0\3\44\7\0"+
    "\6\44\4\0\1\44\1\u0124\3\44\1\u0125\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u0126\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\2\44\1\u0127\26\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u0128\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\14\44\1\u0129\14\44\31\0"+
    "\3\44\7\0\6\44\4\0\16\44\1\u012a\12\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u012b\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\22\44\1\u012c\6\44\31\0"+
    "\3\44\7\0\6\44\4\0\1\44\1\u012d\27\44\31\0"+
    "\3\44\7\0\6\44\4\0\1\44\1\u012e\27\44\31\0"+
    "\3\44\7\0\6\44\4\0\3\44\1\u012f\25\44\31\0"+
    "\3\44\7\0\6\44\4\0\2\44\1\u0130\26\44\31\0"+
    "\3\44\7\0\6\44\4\0\16\44\1\u0131\12\44\31\0"+
    "\3\44\7\0\6\44\4\0\21\44\1\u0132\7\44\31\0"+
    "\3\44\7\0\6\44\4\0\13\44\1\u0133\15\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\u0134\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u0135\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\26\44\1\u0136\2\44\31\0"+
    "\3\44\7\0\6\44\4\0\2\44\1\u0137\26\44\31\0"+
    "\3\44\7\0\6\44\4\0\1\44\1\u0138\27\44\31\0"+
    "\3\44\7\0\6\44\4\0\7\44\1\u0139\21\44\31\0"+
    "\3\44\7\0\6\44\4\0\3\44\1\u013a\25\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u013b\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\21\44\1\u013c\7\44\31\0"+
    "\3\44\7\0\6\44\4\0\25\44\1\u013d\3\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\u013e\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\13\44\1\u013f\15\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u0140\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\24\44\1\u0141\4\44\31\0"+
    "\3\44\7\0\6\44\4\0\24\44\1\u0142\4\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\u0143\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\24\44\1\u0144\4\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u0145\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\u0146\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u0147\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\15\44\1\u0148\13\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u0149\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\11\44\1\u014a\17\44\31\0"+
    "\3\44\7\0\6\44\4\0\15\44\1\u014b\13\44\31\0"+
    "\3\44\7\0\6\44\4\0\4\44\1\u014c\24\44\31\0"+
    "\3\44\7\0\6\44\4\0\15\44\1\u014d\13\44\31\0"+
    "\3\44\7\0\6\44\4\0\13\44\1\u014e\15\44\31\0"+
    "\3\44\7\0\6\44\4\0\10\44\1\u014f\20\44\4\0"+
    "\2\300\1\0\2\300\1\0\47\300\1\u0150\32\300\1\0"+
    "\2\300\1\0\52\300\1\u0151\25\300\25\0\3\u0115\7\0"+
    "\3\u0115\1\0\1\151\6\0\6\u0115\10\0\1\151\24\0"+
    "\1\u0152\4\0\1\u0153\10\0\3\44\7\0\6\44\1\u0154"+
    "\3\0\31\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u0155\7\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u0156\25\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u0157\5\44\31\0\3\44\7\0\6\44\4\0\12\44"+
    "\1\u0158\16\44\31\0\3\44\7\0\6\44\4\0\10\44"+
    "\1\u0159\20\44\31\0\3\44\7\0\6\44\4\0\22\44"+
    "\1\u015a\6\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u015b\27\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u015c\23\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u015d\5\44\31\0\3\44\7\0\6\44\4\0\11\44"+
    "\1\u015e\17\44\31\0\3\44\7\0\6\44\4\0\24\44"+
    "\1\u015f\4\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u0160\7\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u0161\5\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u0162\15\44\31\0\3\44\7\0\6\44\4\0\11\44"+
    "\1\u0163\17\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u0164\7\44\31\0\3\44\7\0\6\44\4\0\15\44"+
    "\1\u0165\13\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u0166\23\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u0167\15\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u0168\5\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u0169\5\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u016a\27\44\31\0\3\44\7\0\6\44\4\0\4\44"+
    "\1\u016b\24\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u016c\23\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u016d\27\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u016e\7\44\31\0\3\44\7\0\6\44\4\0\16\44"+
    "\1\u016f\12\44\31\0\3\44\7\0\6\44\4\0\4\44"+
    "\1\u0170\24\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u0171\15\44\31\0\3\44\7\0\6\44\4\0\10\44"+
    "\1\u0172\20\44\31\0\3\44\7\0\6\44\4\0\22\44"+
    "\1\u0173\6\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u0174\27\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u0175\27\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u0176\23\44\31\0\3\44\7\0\6\44\4\0\11\44"+
    "\1\u0177\17\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u0178\27\44\31\0\3\44\7\0\6\44\4\0\11\44"+
    "\1\u0179\17\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u017a\7\44\31\0\3\44\7\0\6\44\4\0\11\44"+
    "\1\u017b\17\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u017c\25\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u017d\7\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u017e\25\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u017f\15\44\31\0\3\44\7\0\6\44\4\0\7\44"+
    "\1\u0180\21\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u0181\23\44\4\0\2\300\1\0\2\300\1\0\64\300"+
    "\1\u0182\15\300\1\0\2\300\1\0\54\300\1\u0183\23\300"+
    "\7\u0152\1\u0184\76\u0152\14\u0153\1\u0184\71\u0153\33\0\1\u0154"+
    "\11\0\1\u0185\65\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u0186\27\44\31\0\3\44\7\0\6\44\4\0\15\44"+
    "\1\u0187\13\44\31\0\3\44\7\0\6\44\4\0\17\44"+
    "\1\u0188\11\44\31\0\3\44\7\0\6\44\4\0\15\44"+
    "\1\u0189\13\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u018a\15\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u018b\23\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u018c\23\44\31\0\3\44\7\0\6\44\4\0\6\44"+
    "\1\u018d\22\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u018e\5\44\31\0\3\44\7\0\6\44\4\0\4\44"+
    "\1\u018f\24\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u0190\15\44\31\0\3\44\7\0\6\44\4\0\11\44"+
    "\1\u0191\17\44\31\0\3\44\7\0\6\44\4\0\13\44"+
    "\1\u0192\15\44\31\0\3\44\7\0\6\44\4\0\14\44"+
    "\1\u0193\14\44\31\0\3\44\7\0\6\44\4\0\15\44"+
    "\1\u0194\13\44\31\0\3\44\7\0\6\44\4\0\6\44"+
    "\1\u0195\22\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u0196\7\44\31\0\3\44\7\0\6\44\4\0\1\44"+
    "\1\u0197\27\44\31\0\3\44\7\0\6\44\4\0\17\44"+
    "\1\u0198\11\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u0199\5\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u019a\5\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u019b\25\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u019c\25\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u019d\5\44\31\0\3\44\7\0\6\44\4\0\21\44"+
    "\1\u019e\7\44\31\0\3\44\7\0\6\44\4\0\15\44"+
    "\1\u019f\13\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u01a0\25\44\31\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u01a1\5\44\31\0\3\44\7\0\6\44\4\0\22\44"+
    "\1\u01a2\6\44\31\0\3\44\7\0\6\44\4\0\10\44"+
    "\1\u01a3\20\44\4\0\2\300\1\0\2\300\1\0\50\300"+
    "\1\u01a4\31\300\1\0\2\300\1\0\61\300\1\u01a5\16\300"+
    "\25\0\3\44\7\0\6\44\4\0\3\44\1\u01a6\25\44"+
    "\31\0\3\44\7\0\6\44\4\0\4\44\1\u01a7\24\44"+
    "\31\0\3\44\7\0\6\44\4\0\23\44\1\u01a8\5\44"+
    "\31\0\3\44\7\0\6\44\4\0\24\44\1\u01a9\4\44"+
    "\31\0\3\44\7\0\6\44\4\0\23\44\1\u01aa\5\44"+
    "\31\0\3\44\7\0\6\44\4\0\22\44\1\u01ab\6\44"+
    "\31\0\3\44\7\0\6\44\4\0\30\44\1\u01ac\31\0"+
    "\3\44\7\0\6\44\4\0\16\44\1\u01ad\12\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u01ae\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\3\44\1\u01af\25\44\31\0"+
    "\3\44\7\0\6\44\4\0\1\44\1\u01b0\27\44\31\0"+
    "\3\44\7\0\6\44\4\0\4\44\1\u01b1\24\44\31\0"+
    "\3\44\7\0\6\44\4\0\1\44\1\u01b2\27\44\31\0"+
    "\3\44\7\0\6\44\4\0\16\44\1\u01b3\12\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u01b4\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\u01b5\5\44\31\0"+
    "\3\44\7\0\6\44\4\0\5\44\1\u01b6\23\44\31\0"+
    "\3\44\7\0\6\44\4\0\23\44\1\u01b7\5\44\4\0"+
    "\2\300\1\0\2\300\1\0\52\300\1\u01b8\27\300\1\0"+
    "\2\300\1\0\60\300\1\u01b9\17\300\25\0\3\44\7\0"+
    "\6\44\4\0\23\44\1\u01ba\5\44\31\0\3\44\7\0"+
    "\6\44\4\0\5\44\1\u01bb\23\44\31\0\3\44\7\0"+
    "\6\44\4\0\15\44\1\u01bc\13\44\31\0\3\44\7\0"+
    "\6\44\4\0\15\44\1\u01bd\13\44\31\0\3\44\7\0"+
    "\6\44\4\0\5\44\1\u01be\23\44\31\0\3\44\7\0"+
    "\6\44\4\0\3\44\1\u01bf\25\44\31\0\3\44\7\0"+
    "\6\44\4\0\3\44\1\u01c0\25\44\31\0\3\44\7\0"+
    "\6\44\4\0\21\44\1\u01c1\7\44\31\0\3\44\7\0"+
    "\6\44\4\0\5\44\1\u01c2\23\44\31\0\3\44\7\0"+
    "\6\44\4\0\22\44\1\u01c3\6\44\31\0\3\44\7\0"+
    "\6\44\4\0\21\44\1\u01c4\7\44\4\0\2\300\1\0"+
    "\2\300\1\0\54\300\1\u01c5\23\300\2\u01b9\1\0\2\u01b9"+
    "\1\0\100\u01b9\25\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u01c6\5\44\31\0\3\44\7\0\6\44\4\0\16\44"+
    "\1\u01c7\12\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u01c8\23\44\31\0\3\44\7\0\6\44\4\0\5\44"+
    "\1\u01c9\23\44\31\0\3\44\7\0\6\44\4\0\4\44"+
    "\1\u01ca\24\44\31\0\3\44\7\0\6\44\4\0\24\44"+
    "\1\u01cb\4\44\4\0\2\300\1\0\2\300\1\0\61\300"+
    "\1\u01cc\16\300\25\0\3\44\7\0\6\44\4\0\22\44"+
    "\1\u01cd\6\44\31\0\3\44\7\0\6\44\4\0\6\44"+
    "\1\u01ce\22\44\31\0\3\44\7\0\6\44\4\0\3\44"+
    "\1\u01cf\25\44\4\0\2\300\1\0\2\300\1\0\60\300"+
    "\1\u01d0\17\300\25\0\3\44\7\0\6\44\4\0\23\44"+
    "\1\u01d1\5\44\4\0\2\u01d0\1\0\2\u01d0\1\0\100\u01d0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[23450];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\6\0\1\10\1\11\1\1\1\11\10\1\2\11\2\1"+
    "\1\11\6\1\1\11\4\1\1\11\2\1\1\11\26\1"+
    "\1\11\1\1\1\11\2\1\1\11\4\1\1\11\1\0"+
    "\3\1\1\0\3\1\1\11\1\0\1\11\1\0\1\11"+
    "\1\0\1\11\1\0\3\11\2\0\3\11\1\1\2\11"+
    "\1\1\1\0\1\1\1\11\1\1\4\0\2\11\2\1"+
    "\5\11\1\1\1\11\1\1\1\0\2\11\65\1\2\11"+
    "\3\0\1\1\2\0\1\1\1\0\1\11\1\0\2\11"+
    "\2\0\5\1\2\11\1\1\1\11\1\1\1\0\2\1"+
    "\4\11\100\1\1\11\100\1\3\0\57\1\2\11\114\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[465];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
  /**
   * CharSequence 适配器，用于从 CharSequence 读取字符
   */
  static class CharSeqReader extends Reader
  {
    int offset = 0;
    CharSequence src;

    CharSeqReader(CharSequence src)
    {
      this.src = src;
    }

    @Override
    public void close() throws IOException
    {
      src = null;
      offset = 0;
    }

    @Override
    public int read(char[] chars, int i, int i1) throws IOException
    {
      int len = Math.min(src.length() - offset, i1);
      for (int n = 0; n < len; n++)
      {
        try{
          char c = src.charAt(offset++);
          chars[i++] = c;
        }catch(Exception e){
          // ignore
        }
      }
      if (len <= 0)
        return -1;
      return len;
    }
  }

  /**
   * 从 CharSequence 创建词法分析器
   */
  public LuaLexer(CharSequence src) {
    this(new CharSeqReader(src));
  }

  /**
   * 获取当前行号
   */
  public int yyline(){
    return yyline;
  }
  
  /**
   * 获取当前列号
   */
  public int yycolumn(){
    return yycolumn;
  }
  
  /**
   * 获取当前字符位置
   */
  public int yychar(){
    return (int)yychar;
  }
  
  // 块字符串/注释的等号数量
  private int nBrackets = 0;
  // 块内容缓冲区
  private StringBuilder blockBuffer = new StringBuilder();
  // 块开始标记
  private String blockStart = "";
  // 用于存储完整的块内容（开始标记 + 内容 + 结束标记）
  private String fullBlockContent = "";
  
  /**
   * 检查指定偏移处是否为指定字符
   */
  private boolean checkAhead(char c, int offset) {
    int pos = this.zzMarkedPos + offset;
    return pos < this.zzBuffer.length && this.zzBuffer[pos] == c;
  }

  /**
   * 检查并解析块字符串/注释的开始标记 [=*[
   * 设置 nBrackets 为等号数量
   * @return 是否是有效的块开始标记
   */
  private boolean checkBlock() {
    nBrackets = 0;
    if (checkAhead('[', 0)) {
      int n = 0;
      while (checkAhead('=', n + 1)) n++;
      if (checkAhead('[', n + 1)) {
        nBrackets = n;
        return true;
      }
    }
    return false;
  }

  /**
   * 从当前匹配文本中解析块开始标记的等号数量
   */
  private void parseBlockBrackets() {
    String text = yytext();
    nBrackets = 0;
    for (int i = 1; i < text.length() - 1; i++) {
      if (text.charAt(i) == '=') nBrackets++;
    }
  }

  /**
   * 检查块字符串/注释是否已闭合
   * @return 闭合标记后多余的字符数，-1 表示未闭合
   */
  private int checkBlockEnd() {
    String cs = blockBuffer.toString();
    StringBuilder closer = new StringBuilder("]");
    for (int i = 0; i < nBrackets; i++) closer.append('=');
    closer.append(']');
    int index = cs.indexOf(closer.toString());
    if (index >= 0) {
      return cs.length() - index - nBrackets - 2;
    }
    return -1;
  }

  /**
   * 获取完整的块内容（长字符串或块注释）
   * @return 完整的块内容
   */
  public String getBlockContent() {
    return fullBlockContent;
  }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LuaLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public LuaTokenTypes advance() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case xSHEBANG: {
              yybegin(YYINITIAL); return SHEBANG_CONTENT;
            }  // fall though
            case 466: break;
            case xDOUBLE_QUOTED_STRING: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }  // fall though
            case 467: break;
            case xSINGLE_QUOTED_STRING: {
              yybegin(YYINITIAL); return BAD_CHARACTER;
            }  // fall though
            case 468: break;
            case xBLOCK_STRING: {
              fullBlockContent = blockStart + blockBuffer.toString();
                              yybegin(YYINITIAL); 
                              return BAD_CHARACTER;
            }  // fall though
            case 469: break;
            case xBLOCK_COMMENT: {
              fullBlockContent = blockStart + blockBuffer.toString();
                              yybegin(YYINITIAL); 
                              return BLOCK_COMMENT;
            }  // fall though
            case 470: break;
            default:
              {
                return null;
              }
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return BAD_CHARACTER;
            }
          // fall through
          case 164: break;
          case 2:
            { return WHITE_SPACE;
            }
          // fall through
          case 165: break;
          case 3:
            { return NEW_LINE;
            }
          // fall through
          case 166: break;
          case 4:
            { return NOT;
            }
          // fall through
          case 167: break;
          case 5:
            { yybegin(xDOUBLE_QUOTED_STRING);
            }
          // fall through
          case 168: break;
          case 6:
            { return GETN;
            }
          // fall through
          case 169: break;
          case 7:
            { return DOLLAR;
            }
          // fall through
          case 170: break;
          case 8:
            { return MOD;
            }
          // fall through
          case 171: break;
          case 9:
            { return BIT_AND;
            }
          // fall through
          case 172: break;
          case 10:
            { yybegin(xSINGLE_QUOTED_STRING);
            }
          // fall through
          case 173: break;
          case 11:
            { return LPAREN;
            }
          // fall through
          case 174: break;
          case 12:
            { return RPAREN;
            }
          // fall through
          case 175: break;
          case 13:
            { return MULT;
            }
          // fall through
          case 176: break;
          case 14:
            { return PLUS;
            }
          // fall through
          case 177: break;
          case 15:
            { return COMMA;
            }
          // fall through
          case 178: break;
          case 16:
            { return MINUS;
            }
          // fall through
          case 179: break;
          case 17:
            { return DOT;
            }
          // fall through
          case 180: break;
          case 18:
            { return DIV;
            }
          // fall through
          case 181: break;
          case 19:
            { return NUMBER;
            }
          // fall through
          case 182: break;
          case 20:
            { return COLON;
            }
          // fall through
          case 183: break;
          case 21:
            { return SEMI;
            }
          // fall through
          case 184: break;
          case 22:
            { return LT;
            }
          // fall through
          case 185: break;
          case 23:
            { return ASSIGN;
            }
          // fall through
          case 186: break;
          case 24:
            { return GT;
            }
          // fall through
          case 187: break;
          case 25:
            { return QUESTION;
            }
          // fall through
          case 188: break;
          case 26:
            { return AT;
            }
          // fall through
          case 189: break;
          case 27:
            { return NAME;
            }
          // fall through
          case 190: break;
          case 28:
            { return LBRACK;
            }
          // fall through
          case 191: break;
          case 29:
            { return RBRACK;
            }
          // fall through
          case 192: break;
          case 30:
            { return EXP;
            }
          // fall through
          case 193: break;
          case 31:
            { return LCURLY;
            }
          // fall through
          case 194: break;
          case 32:
            { return BIT_OR;
            }
          // fall through
          case 195: break;
          case 33:
            { return RCURLY;
            }
          // fall through
          case 196: break;
          case 34:
            { return BIT_TILDE;
            }
          // fall through
          case 197: break;
          case 35:
            { 
            }
          // fall through
          case 198: break;
          case 36:
            { yybegin(YYINITIAL); return SHEBANG_CONTENT;
            }
          // fall through
          case 199: break;
          case 37:
            { yybegin(YYINITIAL); return BAD_CHARACTER;
            }
          // fall through
          case 200: break;
          case 38:
            { yybegin(YYINITIAL); return STRING;
            }
          // fall through
          case 201: break;
          case 39:
            { blockBuffer.append(yytext());
            }
          // fall through
          case 202: break;
          case 40:
            { return NE;
            }
          // fall through
          case 203: break;
          case 41:
            { return STRING;
            }
          // fall through
          case 204: break;
          case 42:
            { yybegin(xSHEBANG); return SHEBANG;
            }
          // fall through
          case 205: break;
          case 43:
            { return DOLLDOLL;
            }
          // fall through
          case 206: break;
          case 44:
            { return MODEQ;
            }
          // fall through
          case 207: break;
          case 45:
            { return AND;
            }
          // fall through
          case 208: break;
          case 46:
            { return BANDEQ;
            }
          // fall through
          case 209: break;
          case 47:
            { return MULEQ;
            }
          // fall through
          case 210: break;
          case 48:
            { return PLUSPLUS;
            }
          // fall through
          case 211: break;
          case 49:
            { return ADDEQ;
            }
          // fall through
          case 212: break;
          case 50:
            { return SHORT_COMMENT;
            }
          // fall through
          case 213: break;
          case 51:
            { return SUBEQ;
            }
          // fall through
          case 214: break;
          case 52:
            { return LEF;
            }
          // fall through
          case 215: break;
          case 53:
            { return CONCAT;
            }
          // fall through
          case 216: break;
          case 54:
            { return DOUBLE_DIV;
            }
          // fall through
          case 217: break;
          case 55:
            { return DIVEQ;
            }
          // fall through
          case 218: break;
          case 56:
            { return DOUBLE_COLON;
            }
          // fall through
          case 219: break;
          case 57:
            { return WALRUS;
            }
          // fall through
          case 220: break;
          case 58:
            { return BIT_LTLT;
            }
          // fall through
          case 221: break;
          case 59:
            { return LE;
            }
          // fall through
          case 222: break;
          case 60:
            { return MERGE;
            }
          // fall through
          case 223: break;
          case 61:
            { return REVPIPE;
            }
          // fall through
          case 224: break;
          case 62:
            { return EQ;
            }
          // fall through
          case 225: break;
          case 63:
            { return MEAN;
            }
          // fall through
          case 226: break;
          case 64:
            { return GE;
            }
          // fall through
          case 227: break;
          case 65:
            { return BIT_RTRT;
            }
          // fall through
          case 228: break;
          case 66:
            { return OPTCHAIN;
            }
          // fall through
          case 229: break;
          case 67:
            { return NULLCOAL;
            }
          // fall through
          case 230: break;
          case 68:
            { blockStart = yytext();
                              parseBlockBrackets();
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_STRING);
            }
          // fall through
          case 231: break;
          case 69:
            { return POWEQ;
            }
          // fall through
          case 232: break;
          case 70:
            { return AS;
            }
          // fall through
          case 233: break;
          case 71:
            { return DO;
            }
          // fall through
          case 234: break;
          case 72:
            { return IF;
            }
          // fall through
          case 235: break;
          case 73:
            { return IN;
            }
          // fall through
          case 236: break;
          case 74:
            { return IS;
            }
          // fall through
          case 237: break;
          case 75:
            { return OR;
            }
          // fall through
          case 238: break;
          case 76:
            { return BOREQ;
            }
          // fall through
          case 239: break;
          case 77:
            { return PIPE;
            }
          // fall through
          case 240: break;
          case 78:
            { String text = yytext();
                              int eqs = text.length() - 2;
                              blockBuffer.append(text);
                              if (eqs == nBrackets) {
                                fullBlockContent = blockStart + blockBuffer.toString();
                                yybegin(YYINITIAL);
                                return LONG_STRING;
                              }
            }
          // fall through
          case 241: break;
          case 79:
            { String text = yytext();
                              int eqs = text.length() - 2;
                              blockBuffer.append(text);
                              if (eqs == nBrackets) {
                                fullBlockContent = blockStart + blockBuffer.toString();
                                yybegin(YYINITIAL);
                                return BLOCK_COMMENT;
                              }
            }
          // fall through
          case 242: break;
          case 80:
            { return INTERPSTRING;
            }
          // fall through
          case 243: break;
          case 81:
            { return DOC_COMMENT;
            }
          // fall through
          case 244: break;
          case 82:
            { return ELLIPSIS;
            }
          // fall through
          case 245: break;
          case 83:
            { return CONCATEQ;
            }
          // fall through
          case 246: break;
          case 84:
            { return REGEX;
            }
          // fall through
          case 247: break;
          case 85:
            { return IDIVEQ;
            }
          // fall through
          case 248: break;
          case 86:
            { return SHLEQ;
            }
          // fall through
          case 249: break;
          case 87:
            { return SPACESHIP;
            }
          // fall through
          case 250: break;
          case 88:
            { return SHREQ;
            }
          // fall through
          case 251: break;
          case 89:
            { return NULLCOALEQ;
            }
          // fall through
          case 252: break;
          case 90:
            { return ASM;
            }
          // fall through
          case 253: break;
          case 91:
            { return END;
            }
          // fall through
          case 254: break;
          case 92:
            { return FOR;
            }
          // fall through
          case 255: break;
          case 93:
            { return TYPE_INT;
            }
          // fall through
          case 256: break;
          case 94:
            { return LET;
            }
          // fall through
          case 257: break;
          case 95:
            { return NEW;
            }
          // fall through
          case 258: break;
          case 96:
            { return NIL;
            }
          // fall through
          case 259: break;
          case 97:
            { return TRY;
            }
          // fall through
          case 260: break;
          case 98:
            { return SAFEPIPE;
            }
          // fall through
          case 261: break;
          case 99:
            { blockStart = yytext();
                              nBrackets = 0;
                              for (int i = 3; i < blockStart.length() - 1; i++) {
                                if (blockStart.charAt(i) == '=') nBrackets++;
                              }
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_COMMENT);
            }
          // fall through
          case 262: break;
          case 100:
            { return BOOL;
            }
          // fall through
          case 263: break;
          case 101:
            { return CASE;
            }
          // fall through
          case 264: break;
          case 102:
            { return CHAR;
            }
          // fall through
          case 265: break;
          case 103:
            { return ELSE;
            }
          // fall through
          case 266: break;
          case 104:
            { return ENUM;
            }
          // fall through
          case 267: break;
          case 105:
            { return GOTO;
            }
          // fall through
          case 268: break;
          case 106:
            { return LONG;
            }
          // fall through
          case 269: break;
          case 107:
            { return TAKE;
            }
          // fall through
          case 270: break;
          case 108:
            { return THEN;
            }
          // fall through
          case 271: break;
          case 109:
            { return TRUE;
            }
          // fall through
          case 272: break;
          case 110:
            { return VOID;
            }
          // fall through
          case 273: break;
          case 111:
            { return WHEN;
            }
          // fall through
          case 274: break;
          case 112:
            { return WITH;
            }
          // fall through
          case 275: break;
          case 113:
            { return ASYNC;
            }
          // fall through
          case 276: break;
          case 114:
            { return AWAIT;
            }
          // fall through
          case 277: break;
          case 115:
            { return BREAK;
            }
          // fall through
          case 278: break;
          case 116:
            { return CATCH;
            }
          // fall through
          case 279: break;
          case 117:
            { return CLASS;
            }
          // fall through
          case 280: break;
          case 118:
            { return CONST;
            }
          // fall through
          case 281: break;
          case 119:
            { return DEFER;
            }
          // fall through
          case 282: break;
          case 120:
            { return FALSE;
            }
          // fall through
          case 283: break;
          case 121:
            { return FINAL;
            }
          // fall through
          case 284: break;
          case 122:
            { return FLOAT;
            }
          // fall through
          case 285: break;
          case 123:
            { return GUARD;
            }
          // fall through
          case 286: break;
          case 124:
            { return LOCAL;
            }
          // fall through
          case 287: break;
          case 125:
            { return MATCH;
            }
          // fall through
          case 288: break;
          case 126:
            { return SUPER;
            }
          // fall through
          case 289: break;
          case 127:
            { return UNTIL;
            }
          // fall through
          case 290: break;
          case 128:
            { return USING;
            }
          // fall through
          case 291: break;
          case 129:
            { return WHILE;
            }
          // fall through
          case 292: break;
          case 130:
            { return RAW_STRING;
            }
          // fall through
          case 293: break;
          case 131:
            { blockStart = yytext();
                              nBrackets = 0;
                              for (int i = 2; i < blockStart.length() - 1; i++) {
                                if (blockStart.charAt(i) == '=') nBrackets++;
                              }
                              blockBuffer.setLength(0);
                              yybegin(xBLOCK_STRING);
            }
          // fall through
          case 294: break;
          case 132:
            { return DELETE;
            }
          // fall through
          case 295: break;
          case 133:
            { return DOUBLE;
            }
          // fall through
          case 296: break;
          case 134:
            { return ELSEIF;
            }
          // fall through
          case 297: break;
          case 135:
            { return EXPORT;
            }
          // fall through
          case 298: break;
          case 136:
            { return GLOBAL;
            }
          // fall through
          case 299: break;
          case 137:
            { return LAMBDA;
            }
          // fall through
          case 300: break;
          case 138:
            { return PUBLIC;
            }
          // fall through
          case 301: break;
          case 139:
            { return REPEAT;
            }
          // fall through
          case 302: break;
          case 140:
            { return RETURN;
            }
          // fall through
          case 303: break;
          case 141:
            { return STATIC;
            }
          // fall through
          case 304: break;
          case 142:
            { return STRUCT;
            }
          // fall through
          case 305: break;
          case 143:
            { return SWITCH;
            }
          // fall through
          case 306: break;
          case 144:
            { return COMMAND;
            }
          // fall through
          case 307: break;
          case 145:
            { return CONCEPT;
            }
          // fall through
          case 308: break;
          case 146:
            { return DEFAULT;
            }
          // fall through
          case 309: break;
          case 147:
            { return EXTENDS;
            }
          // fall through
          case 310: break;
          case 148:
            { return FINALLY;
            }
          // fall through
          case 311: break;
          case 149:
            { return KEYWORD;
            }
          // fall through
          case 312: break;
          case 150:
            { return PRIVATE;
            }
          // fall through
          case 313: break;
          case 151:
            { return REGION;
            }
          // fall through
          case 314: break;
          case 152:
            { return ABSTRACT;
            }
          // fall through
          case 315: break;
          case 153:
            { return CONTINUE;
            }
          // fall through
          case 316: break;
          case 154:
            { return FUNCTION;
            }
          // fall through
          case 317: break;
          case 155:
            { return OPERATOR_KW;
            }
          // fall through
          case 318: break;
          case 156:
            { return REQUIRES;
            }
          // fall through
          case 319: break;
          case 157:
            { return INTERFACE;
            }
          // fall through
          case 320: break;
          case 158:
            { return NAMESPACE;
            }
          // fall through
          case 321: break;
          case 159:
            { return PROTECTED;
            }
          // fall through
          case 322: break;
          case 160:
            { return IMPLEMENTS;
            }
          // fall through
          case 323: break;
          case 161:
            { return INSTANCEOF;
            }
          // fall through
          case 324: break;
          case 162:
            { return ENDREGION;
            }
          // fall through
          case 325: break;
          case 163:
            { return SUPERSTRUCT;
            }
          // fall through
          case 326: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
