/* The following code was generated by JFlex 1.6.1 */
package com.nirithy.lxclua

import java.io.IOException
import java.io.Reader
import kotlin.math.min

/**
 * This class is a scanner generated by
 * [JFlex](http://www.jflex.de/) 1.6.1
 * from the specification file <tt>D:/JFLEX/bin/lua.flex</tt>
 */
class LuaLexer
/**
 * Creates a new scanner
 *
 * @param zzReader the java.io.Reader to read input from.
 */(
    /**
     * the input device
     */
    private var zzReader: Reader?
) {
    /**
     * the current state of the DFA
     */
    private var zzState = 0

    /**
     * the current lexical state
     */
    private var zzLexicalState: Int = YYINITIAL

    /**
     * this buffer contains the current text to be matched and is
     * the source of the yytext() string
     */
    private var zzBuffer = CharArray(ZZ_BUFFERSIZE)

    /**
     * the textposition at the last accepting state
     */
    private var zzMarkedPos = 0

    /**
     * the current text position in the buffer
     */
    private var zzCurrentPos = 0

    /**
     * startRead marks the beginning of the yytext() string in the buffer
     */
    private var zzStartRead = 0

    /**
     * endRead marks the last character in the buffer, that has been read
     * from input
     */
    private var zzEndRead = 0

    /**
     * number of newlines encountered up to the start of the matched text
     */
    private var yyline = 0

    /**
     * the number of characters up to the start of the matched text
     */
    private var yychar = 0

    /**
     * the number of characters from the last newline up to the start of the
     * matched text
     */
    private var yycolumn = 0

    /**
     * zzAtBOL == true <=> the scanner is currently at the beginning of a line
     */
    private var zzAtBOL = true

    /**
     * zzAtEOF == true <=> the scanner is at the EOF
     */
    private var zzAtEOF = false

    /**
     * denotes if the user-EOF-code has already been executed
     */
    private var zzEOFDone = false

    /**
     * The number of occupied positions in zzBuffer beyond zzEndRead.
     * When a lead/high surrogate has been read from the input stream
     * into the final zzBuffer position, this will have a value of 1;
     * otherwise, it will have a value of 0.
     */
    private var zzFinalHighSurrogate = 0


    /* user code: */
    internal class CharSeqReader(var src: CharSequence?) : Reader() {
        var offset: Int = 0

        @Throws(IOException::class)
        override fun close() {
            src = null
            offset = 0
        }

        @Throws(IOException::class)
        override fun read(chars: CharArray, i: Int, i1: Int): Int {
            var i = i
            val len = min(src!!.length - offset, i1)
            for (n in 0..<len) {
                try {
                    val c = src!!.get(offset++)
                    chars[i++] = c
                } catch (e: Exception) {
                }
            }
            if (len <= 0) return -1
            return len
        }
    }

    constructor(src: CharSequence?) : this(CharSeqReader(src))

    fun yyline(): Int {
        return yyline
    }

    fun yycolumn(): Int {
        return yycolumn
    }

    fun yychar(): Int {
        return yychar
    }

    private var nBrackets = 0

    private fun checkAhead(c: Char, offset: Int): Boolean {
        return this.zzMarkedPos + offset < this.zzBuffer.size && this.zzBuffer[this.zzMarkedPos + offset] == c
    }

    private fun checkBlock(): Boolean {
        nBrackets = 0
        if (checkAhead('[', 0)) {
            var n = 0
            while (checkAhead('=', n + 1)) n++
            if (checkAhead('[', n + 1)) {
                nBrackets = n
                return true
            }
        }
        return false
    }

    private fun checkBlockRedundant(): Int {
        var redundant = -1
        val cs = yytext()
        val s = StringBuilder("]")
        for (i in 0..<nBrackets) s.append('=')
        s.append(']')
        val index = cs.indexOf(s.toString())
        if (index > 0) redundant = yylength() - index - nBrackets - 2
        return redundant
    }


    /**
     * Refills the input buffer.
     *
     * @return `false`, iff there was new input.
     * @throws IOException if any I/O-Error occurs
     */
    @Throws(IOException::class)
    private fun zzRefill(): Boolean {
        /* first: make room (if you can) */

        if (zzStartRead > 0) {
            zzEndRead += zzFinalHighSurrogate
            zzFinalHighSurrogate = 0
            System.arraycopy(
                zzBuffer, zzStartRead,
                zzBuffer, 0,
                zzEndRead - zzStartRead
            )

            /* translate stored positions */
            zzEndRead -= zzStartRead
            zzCurrentPos -= zzStartRead
            zzMarkedPos -= zzStartRead
            zzStartRead = 0
        }

        /* is the buffer big enough? */
        if (zzCurrentPos >= zzBuffer.size - zzFinalHighSurrogate) {
            /* if not: blow it up */
            val newBuffer = CharArray(zzBuffer.size * 2)
            System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.size)
            zzBuffer = newBuffer
            zzEndRead += zzFinalHighSurrogate
            zzFinalHighSurrogate = 0
        }

        /* fill the buffer with new input */
        val requested = zzBuffer.size - zzEndRead
        val numRead = zzReader!!.read(zzBuffer, zzEndRead, requested)

        /* not supposed to occur according to specification of java.io.Reader */
        if (numRead == 0) {
            throw IOException("Reader returned 0 characters. See JFlex examples for workaround.")
        }
        if (numRead > 0) {
            zzEndRead += numRead
            /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
            if (numRead == requested) {
                if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
                    --zzEndRead
                    zzFinalHighSurrogate = 1
                }
            }
            /* potentially more input available */
            return false
        }

        /* numRead < 0 ==> end of stream */
        return true
    }


    /**
     * Closes the input stream.
     */
    @Throws(IOException::class)
    fun yyclose() {
        zzAtEOF = true /* indicate end of file */
        zzEndRead = zzStartRead /* invalidate buffer    */

        if (zzReader != null) zzReader!!.close()
    }


    /**
     * Resets the scanner to read from a new input stream.
     * Does not close the old reader.
     *
     *
     * All internal variables are reset, the old input stream
     * **cannot** be reused (internal buffer is discarded and lost).
     * Lexical state is set to <tt>ZZ_INITIAL</tt>.
     *
     *
     * Internal scan buffer is resized down to its initial length, if it has grown.
     *
     * @param reader the new input stream
     */
    fun yyreset(reader: Reader?) {
        zzReader = reader
        zzAtBOL = true
        zzAtEOF = false
        zzEOFDone = false
        zzStartRead = 0
        zzEndRead = zzStartRead
        zzMarkedPos = 0
        zzCurrentPos = zzMarkedPos
        zzFinalHighSurrogate = 0
        yycolumn = 0
        yychar = yycolumn
        yyline = yychar
        zzLexicalState = YYINITIAL
        if (zzBuffer.size > ZZ_BUFFERSIZE) zzBuffer = CharArray(ZZ_BUFFERSIZE)
    }


    /**
     * Returns the current lexical state.
     */
    fun yystate(): Int {
        return zzLexicalState
    }


    /**
     * Enters a new lexical state
     *
     * @param newState the new lexical state
     */
    fun yybegin(newState: Int) {
        zzLexicalState = newState
    }


    /**
     * Returns the text matched by the current regular expression.
     */
    fun yytext(): String {
        return String(zzBuffer, zzStartRead, zzMarkedPos - zzStartRead)
    }


    /**
     * Returns the character at position <tt>pos</tt> from the
     * matched text.
     *
     *
     * It is equivalent to yytext().charAt(pos), but faster
     *
     * @param pos the position of the character to fetch.
     * A value from 0 to yylength()-1.
     * @return the character at position pos
     */
    fun yycharat(pos: Int): Char {
        return zzBuffer[zzStartRead + pos]
    }


    /**
     * Returns the length of the matched text region.
     */
    fun yylength(): Int {
        return zzMarkedPos - zzStartRead
    }


    /**
     * Reports an error that occured while scanning.
     *
     *
     * In a wellformed scanner (no or only correct usage of
     * yypushback(int) and a match-all fallback rule) this method
     * will only be called with things that "Can't Possibly Happen".
     * If this method is called, something is seriously wrong
     * (e.g. a JFlex bug producing a faulty scanner etc.).
     *
     *
     * Usual syntax/scanner level error handling should be done
     * in error fallback rules.
     *
     * @param errorCode the code of the errormessage to display
     */
    private fun zzScanError(errorCode: Int) {
        var message: String?
        try {
            message = ZZ_ERROR_MSG[errorCode]
        } catch (e: ArrayIndexOutOfBoundsException) {
            message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR]
        }

        throw Error(message)
    }


    /**
     * Pushes the specified amount of characters back into the input stream.
     *
     *
     * They will be read again by then next call of the scanning method
     *
     * @param number the number of characters to be read again.
     * This number must not be greater than yylength()!
     */
    fun yypushback(number: Int) {
        if (number > yylength()) zzScanError(ZZ_PUSHBACK_2BIG)

        zzMarkedPos -= number
    }


    /**
     * Resumes scanning until the next regular expression is matched,
     * the end of input is encountered or an I/O-Error occurs.
     *
     * @return the next token
     * @throws IOException if any I/O-Error occurs
     */
    @Throws(IOException::class)
    fun advance(): LuaTokenTypes? {
        var zzInput: Int = 0
        var zzAction: Int

        // cached fields:
        var zzCurrentPosL: Int
        var zzMarkedPosL: Int
        var zzEndReadL = zzEndRead
        var zzBufferL = zzBuffer
        val zzCMapL: CharArray = ZZ_CMAP

        val zzTransL: IntArray = ZZ_TRANS
        val zzRowMapL: IntArray = ZZ_ROWMAP
        val zzAttrL: IntArray = ZZ_ATTRIBUTE

        while (true) {
            zzMarkedPosL = zzMarkedPos

            yychar += zzMarkedPosL - zzStartRead

            var zzR = false
            var zzCh: Int
            var zzCharCount: Int
            zzCurrentPosL = zzStartRead
            while (zzCurrentPosL < zzMarkedPosL
            ) {
                zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL)
                zzCharCount = Character.charCount(zzCh)
                when (zzCh) {
                    '\u000B'.code, '\u000C'.code, '\u0085'.code, '\u2028'.code, '\u2029'.code -> {
                        yyline++
                        yycolumn = 0
                        zzR = false
                    }

                    '\r'.code -> {
                        yyline++
                        yycolumn = 0
                        zzR = true
                    }

                    '\n'.code -> if (zzR) zzR = false
                    else {
                        yyline++
                        yycolumn = 0
                    }

                    else -> {
                        zzR = false
                        yycolumn += zzCharCount
                    }
                }
                zzCurrentPosL += zzCharCount
            }

            if (zzR) {
                // peek one character ahead if it is \n (if we have counted one line too much)
                val zzPeek: Boolean
                if (zzMarkedPosL < zzEndReadL) zzPeek = zzBufferL[zzMarkedPosL] == '\n'
                else if (zzAtEOF) zzPeek = false
                else {
                    val eof = zzRefill()
                    zzEndReadL = zzEndRead
                    zzMarkedPosL = zzMarkedPos
                    zzBufferL = zzBuffer
                    if (eof) zzPeek = false
                    else zzPeek = zzBufferL[zzMarkedPosL] == '\n'
                }
                if (zzPeek) yyline--
            }
            zzAction = -1

            zzStartRead = zzMarkedPosL
            zzCurrentPos = zzStartRead
            zzCurrentPosL = zzCurrentPos

            zzState = ZZ_LEXSTATE[zzLexicalState]

            // set up zzAction for empty match case:
            var zzAttributes = zzAttrL[zzState]
            if ((zzAttributes and 1) == 1) {
                zzAction = zzState
            }


            while (true) {
                    if (zzCurrentPosL < zzEndReadL) {
                        zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL)
                        zzCurrentPosL += Character.charCount(zzInput)
                    } else if (zzAtEOF) {
                        zzInput = YYEOF
                        break
                    } else {
                        // store back cached positions
                        zzCurrentPos = zzCurrentPosL
                        zzMarkedPos = zzMarkedPosL
                        val eof = zzRefill()
                        // get translated positions and possibly new buffer
                        zzCurrentPosL = zzCurrentPos
                        zzMarkedPosL = zzMarkedPos
                        zzBufferL = zzBuffer
                        zzEndReadL = zzEndRead
                        if (eof) {
                            zzInput = YYEOF
                            break
                        } else {
                            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL)
                            zzCurrentPosL += Character.charCount(zzInput)
                        }
                    }
                    val zzNext = zzTransL[zzRowMapL[zzState] + zzCMapL[zzInput].code]
                    if (zzNext == -1) break
                    zzState = zzNext

                    zzAttributes = zzAttrL[zzState]
                    if ((zzAttributes and 1) == 1) {
                        zzAction = zzState
                        zzMarkedPosL = zzCurrentPosL
                        if ((zzAttributes and 8) == 8) break
                    }
                }

            // store back cached position
            zzMarkedPos = zzMarkedPosL

            if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
                zzAtEOF = true
                return null
            } else {
                when (if (zzAction < 0) zzAction else ZZ_ACTION[zzAction]) {
                    1 -> {
                        yybegin(YYINITIAL)
                        return LuaTokenTypes.SHEBANG_CONTENT
                    }

                    85 -> {}
                    2 -> {
                        return LuaTokenTypes.BAD_CHARACTER
                    }

                    86 -> {}
                    3 -> {
                        return LuaTokenTypes.NEW_LINE
                    }

                    87 -> {}
                    4 -> {
                        return LuaTokenTypes.WHITE_SPACE
                    }

                    88 -> {}
                    5 -> {
                        val text = yytext()
                        if ("try" == text) {
                            return LuaTokenTypes.TRY
                        } else if ("catch" == text) {
                            return LuaTokenTypes.CATCH
                        } else if ("finally" == text) {
                            return LuaTokenTypes.FINALLY
                        } else if ("guard" == text) {
                            return LuaTokenTypes.GUARD
                        } else if ("delete" == text) {
                            return LuaTokenTypes.DELETE
                        } else {
                            return LuaTokenTypes.NAME
                        }
                    }

                    89 -> {}
                    6 -> {
                        return LuaTokenTypes.NUMBER
                    }

                    90 -> {}
                    7 -> {
                        return LuaTokenTypes.PLUS
                    }

                    91 -> {}
                    8 -> {
                        return LuaTokenTypes.DOT
                    }

                    92 -> {}
                    9 -> {
                        return LuaTokenTypes.MINUS
                    }

                    93 -> {}
                    10 -> {
                        return LuaTokenTypes.LBRACK
                    }

                    94 -> {}
                    11 -> {
                        return LuaTokenTypes.ASSIGN
                    }

                    95 -> {}
                    12 -> {
                        return LuaTokenTypes.RBRACK
                    }

                    96 -> {}
                    13 -> {
                        yybegin(xDOUBLE_QUOTED_STRING)
                        yypushback(yylength())
                    }

                    97 -> {}
                    14 -> {
                        yybegin(xSINGLE_QUOTED_STRING)
                        yypushback(yylength())
                    }

                    98 -> {}
                    15 -> {
                        return LuaTokenTypes.GETN
                    }

                    99 -> {}
                    16 -> {
                        return LuaTokenTypes.NOT
                    }

                    100 -> {}
                    17 -> {
                        return LuaTokenTypes.GT
                    }

                    101 -> {}
                    18 -> {
                        return LuaTokenTypes.LT
                    }

                    102 -> {}
                    19 -> {
                        return LuaTokenTypes.BIT_TILDE
                    }

                    103 -> {}
                    20 -> {
                        return LuaTokenTypes.MULT
                    }

                    104 -> {}
                    21 -> {
                        return LuaTokenTypes.MOD
                    }

                    105 -> {}
                    22 -> {
                        return LuaTokenTypes.DIV
                    }

                    106 -> {}
                    23 -> {
                        return LuaTokenTypes.LPAREN
                    }

                    107 -> {}
                    24 -> {
                        return LuaTokenTypes.RPAREN
                    }

                    108 -> {}
                    25 -> {
                        return LuaTokenTypes.LCURLY
                    }

                    109 -> {}
                    26 -> {
                        return LuaTokenTypes.RCURLY
                    }

                    110 -> {}
                    27 -> {
                        return LuaTokenTypes.COMMA
                    }

                    111 -> {}
                    28 -> {
                        return LuaTokenTypes.SEMI
                    }

                    112 -> {}
                    29 -> {
                        return LuaTokenTypes.COLON
                    }

                    113 -> {}
                    30 -> {
                        return LuaTokenTypes.EXP
                    }

                    114 -> {}
                    31 -> {
                        return LuaTokenTypes.BIT_AND
                    }

                    115 -> {}
                    32 -> {
                        return LuaTokenTypes.BIT_OR
                    }

                    116 -> {}
                    33 -> {
                        return LuaTokenTypes.AT
                    }

                    117 -> {}
                    34 -> {
                        yybegin(YYINITIAL)
                        return LuaTokenTypes.STRING
                    }

                    118 -> {}
                    35 -> {
                        yypushback(yylength())
                        yybegin(xCOMMENT)
                    }

                    119 -> {}
                    36 -> {
                        return LuaTokenTypes.CONCAT
                    }

                    120 -> {}
                    37 -> {
                        val block = checkBlock()
                        if (block) {
                            yypushback(yylength())
                            yybegin(xBLOCK_COMMENT)
                        } else {
                            yypushback(yylength())
                            yybegin(xCOMMENT)
                        }
                    }

                    121 -> {}
                    38 -> {
                        return LuaTokenTypes.IN
                    }

                    122 -> {}
                    39 -> {
                        return LuaTokenTypes.IF
                    }

                    123 -> {}
                    40 -> {
                        return LuaTokenTypes.OR
                    }

                    124 -> {}
                    41 -> {
                        return LuaTokenTypes.DO
                    }

                    125 -> {}
                    42 -> {
                        yybegin(xBLOCK_STRING)
                        yypushback(yylength())
                        checkBlock()
                    }

                    126 -> {}
                    43 -> {
                        return LuaTokenTypes.EQ
                    }

                    127 -> {}
                    44 -> {
                        yybegin(xSHEBANG)
                        return LuaTokenTypes.SHEBANG
                    }

                    128 -> {}
                    45 -> {
                        return LuaTokenTypes.NE
                    }

                    129 -> {}
                    46 -> {
                        return LuaTokenTypes.GE
                    }

                    130 -> {}
                    47 -> {
                        return LuaTokenTypes.BIT_RTRT
                    }

                    131 -> {}
                    48 -> {
                        return LuaTokenTypes.LE
                    }

                    132 -> {}
                    49 -> {
                        return LuaTokenTypes.BIT_LTLT
                    }

                    133 -> {}
                    50 -> {
                        return LuaTokenTypes.DOUBLE_DIV
                    }

                    134 -> {}
                    51 -> {
                        return LuaTokenTypes.DOUBLE_COLON
                    }

                    135 -> {}
                    52 -> {
                        return LuaTokenTypes.AND
                    }

                    136 -> {}
                    53 -> {
                        yybegin(YYINITIAL)
                        return LuaTokenTypes.SHORT_COMMENT
                    }

                    137 -> {}
                    54 -> {
                        return LuaTokenTypes.ELLIPSIS
                    }

                    138 -> {}
                    55 -> {
                        return LuaTokenTypes.END
                    }

                    139 -> {}
                    56 -> {
                        return LuaTokenTypes.NIL
                    }

                    140 -> {}
                    57 -> {
                        return LuaTokenTypes.LEF
                    }

                    141 -> {}
                    58 -> {
                        return LuaTokenTypes.MEAN
                    }

                    142 -> {}
                    59 -> {
                        return LuaTokenTypes.FOR
                    }

                    143 -> {}
                    60 -> {
                        yybegin(YYINITIAL)
                        return LuaTokenTypes.DOC_COMMENT
                    }

                    144 -> {}
                    61 -> {
                        return LuaTokenTypes.ELSE
                    }

                    145 -> {}
                    62 -> {
                        return LuaTokenTypes.GOTO
                    }

                    146 -> {}
                    63 -> {
                        return LuaTokenTypes.CASE
                    }

                    147 -> {}
                    64 -> {
                        return LuaTokenTypes.TRUE
                    }

                    148 -> {}
                    65 -> {
                        return LuaTokenTypes.THEN
                    }

                    149 -> {}
                    66 -> {
                        return LuaTokenTypes.WHEN
                    }

                    150 -> {}
                    67 -> {
                        val redundant = checkBlockRedundant()
                        if (redundant != -1) {
                            yypushback(redundant)
                            yybegin(YYINITIAL)
                            return LuaTokenTypes.LONG_STRING
                        } else {
                            yybegin(YYINITIAL)
                            return LuaTokenTypes.BAD_CHARACTER
                        }
                    }

                    151 -> {}
                    68 -> {
                        val redundant = checkBlockRedundant()
                        if (redundant != -1) {
                            yypushback(redundant)
                            yybegin(YYINITIAL)
                            return LuaTokenTypes.BLOCK_COMMENT
                        } else {
                            yybegin(YYINITIAL)
                            return LuaTokenTypes.BLOCK_COMMENT
                        }
                    }

                    152 -> {}
                    69 -> {
                        return LuaTokenTypes.DEFER
                    }

                    153 -> {}
                    70 -> {
                        return LuaTokenTypes.BREAK
                    }

                    154 -> {}
                    71 -> {
                        return LuaTokenTypes.LOCAL
                    }

                    155 -> {}
                    72 -> {
                        return LuaTokenTypes.FALSE
                    }

                    156 -> {}
                    73 -> {
                        return LuaTokenTypes.UNTIL
                    }

                    157 -> {}
                    74 -> {
                        return LuaTokenTypes.WHILE
                    }

                    158 -> {}
                    75 -> {
                        return LuaTokenTypes.RETURN
                    }

                    159 -> {}
                    76 -> {
                        return LuaTokenTypes.REPEAT
                    }

                    160 -> {}
                    77 -> {
                        return LuaTokenTypes.ELSEIF
                    }

                    161 -> {}
                    78 -> {
                        return LuaTokenTypes.LAMBDA
                    }

                    162 -> {}
                    79 -> {
                        return LuaTokenTypes.SWITCH
                    }

                    163 -> {}
                    80 -> {
                        return LuaTokenTypes.DEFAULT
                    }

                    164 -> {}
                    81 -> {
                        return LuaTokenTypes.REGION
                    }

                    165 -> {}
                    82 -> {
                        return LuaTokenTypes.FUNCTION
                    }

                    166 -> {}
                    83 -> {
                        return LuaTokenTypes.CONTINUE
                    }

                    167 -> {}
                    84 -> {
                        return LuaTokenTypes.ENDREGION
                    }

                    168 -> {}
                    else -> zzScanError(ZZ_NO_MATCH)
                }
            }
        }
    }


    companion object {
        /**
         * This character denotes the end of file
         */
        val YYEOF: Int = -1

        /**
         * initial size of the lookahead buffer
         */
        private const val ZZ_BUFFERSIZE = 16384

        /**
         * lexical states
         */
        const val YYINITIAL: Int = 0
        const val xSHEBANG: Int = 2
        const val xDOUBLE_QUOTED_STRING: Int = 4
        const val xSINGLE_QUOTED_STRING: Int = 6
        const val xBLOCK_STRING: Int = 8
        const val xCOMMENT: Int = 10
        const val xBLOCK_COMMENT: Int = 12

        /**
         * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
         * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
         * at the beginning of a line
         * l is of the form l = 2*k, k a non negative integer
         */
        private val ZZ_LEXSTATE = intArrayOf(
            0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6
        )

        /**
         * Translates characters to character classes
         */
        private val ZZ_CMAP_PACKED =
            "\u0009\u001c\u0001\u0003\u0001\u0002\u0001\u0000\u0001\u0003\u0001\u0001\u000e\u001c\u0004\u001b\u0001\u0003\u0001\u002b" +
                    "\u0001\u0019\u0001\u002a\u0001\u0004\u0001\u0030\u0001\u003a\u0001\u001d\u0001\u0032\u0001\u0033\u0001\u002f\u0001\u0009" +
                    "\u0001\u0036\u0001\u000e\u0001\u000d\u0001\u0031\u0001\u000b\u0009\u0006\u0001\u0038\u0001\u0037\u0001\u002d\u0001\u0017" +
                    "\u0001\u002c\u0001\u001b\u0001\u003d\u0004\u0007\u0001\u0008\u0001\u0007\u0009\u0004\u0001\u000a\u0007\u0004\u0001\u000c" +
                    "\u0002\u0004\u0001\u0016\u0001\u001a\u0001\u0018\u0001\u0039\u0001\u0004\u0001\u001b\u0001\u001e\u0001\u001f\u0001\u0025" +
                    "\u0001\u0015\u0001\u0010\u0001\u0023\u0001\u0011\u0001\u0028\u0001\u0012\u0001\u0004\u0001\u0020\u0001\u0021\u0001\u003c" +
                    "\u0001\u0014\u0001\u0013\u0001\u0027\u0001\u0004\u0001\u000f\u0001\u0022\u0001\u0026\u0001\u0024\u0001\u0004\u0001\u0029" +
                    "\u0001\u000c\u0002\u0004\u0001\u0034\u0001\u003b\u0001\u0035\u0001\u002e\u0006\u001c\u0001\u0005\u001a\u001c\u0001\u0000" +
                    "\u0001\u001b\u0004\u0004\u0004\u001b\u0001\u0004\u0002\u001b\u0001\u001c\u0007\u001b\u0001\u0004\u0004\u001b\u0001\u0004" +
                    "\u0005\u001b\u0017\u0004\u0001\u001b\u001f\u0004\u0001\u001b\u01ca\u0004\u0004\u001b\u000c\u0004\u000e\u001b\u0005\u0004" +
                    "\u0007\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0011\u001b\u0070\u001c\u0005\u0004\u0001\u001b\u0002\u0004\u0002\u001b" +
                    "\u0004\u0004\u0008\u001b\u0001\u0004\u0001\u001b\u0003\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0014\u0004\u0001\u001b" +
                    "\u0053\u0004\u0001\u001b\u008b\u0004\u0001\u001b\u0005\u001c\u0002\u001b\u009e\u0004\u0009\u001b\u0026\u0004\u0002\u001b" +
                    "\u0001\u0004\u0007\u001b\u0027\u0004\u0007\u001b\u0001\u0004\u0001\u001b\u002d\u001c\u0001\u001b\u0001\u001c\u0001\u001b" +
                    "\u0002\u001c\u0001\u001b\u0002\u001c\u0001\u001b\u0001\u001c\u0008\u001b\u001b\u0004\u0005\u001b\u0003\u0004\u000d\u001b" +
                    "\u0005\u001c\u0006\u001b\u0001\u0004\u0004\u001b\u000b\u001c\u0005\u001b\u002b\u0004\u001f\u001c\u0004\u001b\u0002\u0004" +
                    "\u0001\u001c\u0063\u0004\u0001\u001b\u0001\u0004\u0008\u001c\u0001\u001b\u0006\u001c\u0002\u0004\u0002\u001c\u0001\u001b" +
                    "\u0004\u001c\u0002\u0004\u000a\u001c\u0003\u0004\u0002\u001b\u0001\u0004\u000f\u001b\u0001\u001c\u0001\u0004\u0001\u001c" +
                    "\u001e\u0004\u001b\u001c\u0002\u001b\u0059\u0004\u000b\u001c\u0001\u0004\u000e\u001b\u000a\u001c\u0021\u0004\u0009\u001c" +
                    "\u0002\u0004\u0004\u001b\u0001\u0004\u0005\u001b\u0016\u0004\u0004\u001c\u0001\u0004\u0009\u001c\u0001\u0004\u0003\u001c" +
                    "\u0001\u0004\u0005\u001c\u0012\u001b\u0019\u0004\u0003\u001c\u0044\u001b\u0001\u0004\u0001\u001b\u000b\u0004\u0037\u001b" +
                    "\u001b\u001c\u0001\u001b\u0004\u001c\u0036\u0004\u0003\u001c\u0001\u0004\u0012\u001c\u0001\u0004\u0007\u001c\u000a\u0004" +
                    "\u0002\u001c\u0002\u001b\u000a\u001c\u0001\u001b\u0007\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0003\u001c\u0001\u001b" +
                    "\u0008\u0004\u0002\u001b\u0002\u0004\u0002\u001b\u0016\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0001\u0004\u0003\u001b" +
                    "\u0004\u0004\u0002\u001b\u0001\u001c\u0001\u0004\u0007\u001c\u0002\u001b\u0002\u001c\u0002\u001b\u0003\u001c\u0001\u0004" +
                    "\u0008\u001b\u0001\u001c\u0004\u001b\u0002\u0004\u0001\u001b\u0003\u0004\u0002\u001c\u0002\u001b\u000a\u001c\u0004\u0004" +
                    "\u0007\u001b\u0001\u0004\u0005\u001b\u0003\u001c\u0001\u001b\u0006\u0004\u0004\u001b\u0002\u0004\u0002\u001b\u0016\u0004" +
                    "\u0001\u001b\u0007\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u0002\u0004\u0002\u001b\u0001\u001c" +
                    "\u0001\u001b\u0005\u001c\u0004\u001b\u0002\u001c\u0002\u001b\u0003\u001c\u0003\u001b\u0001\u001c\u0007\u001b\u0004\u0004" +
                    "\u0001\u001b\u0001\u0004\u0007\u001b\u000c\u001c\u0003\u0004\u0001\u001c\u000b\u001b\u0003\u001c\u0001\u001b\u0009\u0004" +
                    "\u0001\u001b\u0003\u0004\u0001\u001b\u0016\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u0005\u0004" +
                    "\u0002\u001b\u0001\u001c\u0001\u0004\u0008\u001c\u0001\u001b\u0003\u001c\u0001\u001b\u0003\u001c\u0002\u001b\u0001\u0004" +
                    "\u000f\u001b\u0002\u0004\u0002\u001c\u0002\u001b\u000a\u001c\u0001\u001b\u0001\u0004\u000f\u001b\u0003\u001c\u0001\u001b" +
                    "\u0008\u0004\u0002\u001b\u0002\u0004\u0002\u001b\u0016\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0002\u0004\u0001\u001b" +
                    "\u0005\u0004\u0002\u001b\u0001\u001c\u0001\u0004\u0007\u001c\u0002\u001b\u0002\u001c\u0002\u001b\u0003\u001c\u0008\u001b" +
                    "\u0002\u001c\u0004\u001b\u0002\u0004\u0001\u001b\u0003\u0004\u0002\u001c\u0002\u001b\u000a\u001c\u0001\u001b\u0001\u0004" +
                    "\u0010\u001b\u0001\u001c\u0001\u0004\u0001\u001b\u0006\u0004\u0003\u001b\u0003\u0004\u0001\u001b\u0004\u0004\u0003\u001b" +
                    "\u0002\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0002\u0004\u0003\u001b\u0002\u0004\u0003\u001b\u0003\u0004\u0003\u001b" +
                    "\u000c\u0004\u0004\u001b\u0005\u001c\u0003\u001b\u0003\u001c\u0001\u001b\u0004\u001c\u0002\u001b\u0001\u0004\u0006\u001b" +
                    "\u0001\u001c\u000e\u001b\u000a\u001c\u0009\u001b\u0001\u0004\u0007\u001b\u0003\u001c\u0001\u001b\u0008\u0004\u0001\u001b" +
                    "\u0003\u0004\u0001\u001b\u0017\u0004\u0001\u001b\u000a\u0004\u0001\u001b\u0005\u0004\u0003\u001b\u0001\u0004\u0007\u001c" +
                    "\u0001\u001b\u0003\u001c\u0001\u001b\u0004\u001c\u0007\u001b\u0002\u001c\u0001\u001b\u0002\u0004\u0006\u001b\u0002\u0004" +
                    "\u0002\u001c\u0002\u001b\u000a\u001c\u0012\u001b\u0002\u001c\u0001\u001b\u0008\u0004\u0001\u001b\u0003\u0004\u0001\u001b" +
                    "\u0017\u0004\u0001\u001b\u000a\u0004\u0001\u001b\u0005\u0004\u0002\u001b\u0001\u001c\u0001\u0004\u0007\u001c\u0001\u001b" +
                    "\u0003\u001c\u0001\u001b\u0004\u001c\u0007\u001b\u0002\u001c\u0007\u001b\u0001\u0004\u0001\u001b\u0002\u0004\u0002\u001c" +
                    "\u0002\u001b\u000a\u001c\u0001\u001b\u0002\u0004\u000f\u001b\u0002\u001c\u0001\u001b\u0008\u0004\u0001\u001b\u0003\u0004" +
                    "\u0001\u001b\u0029\u0004\u0002\u001b\u0001\u0004\u0007\u001c\u0001\u001b\u0003\u001c\u0001\u001b\u0004\u001c\u0001\u0004" +
                    "\u0008\u001b\u0001\u001c\u0008\u001b\u0002\u0004\u0002\u001c\u0002\u001b\u000a\u001c\u000a\u001b\u0006\u0004\u0002\u001b" +
                    "\u0002\u001c\u0001\u001b\u0012\u0004\u0003\u001b\u0018\u0004\u0001\u001b\u0009\u0004\u0001\u001b\u0001\u0004\u0002\u001b" +
                    "\u0007\u0004\u0003\u001b\u0001\u001c\u0004\u001b\u0006\u001c\u0001\u001b\u0001\u001c\u0001\u001b\u0008\u001c\u0012\u001b" +
                    "\u0002\u001c\u000d\u001b\u0030\u0004\u0001\u001c\u0002\u0004\u0007\u001c\u0004\u001b\u0008\u0004\u0008\u001c\u0001\u001b" +
                    "\u000a\u001c\u0027\u001b\u0002\u0004\u0001\u001b\u0001\u0004\u0002\u001b\u0002\u0004\u0001\u001b\u0001\u0004\u0002\u001b" +
                    "\u0001\u0004\u0006\u001b\u0004\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0003\u0004\u0001\u001b\u0001\u0004\u0001\u001b" +
                    "\u0001\u0004\u0002\u001b\u0002\u0004\u0001\u001b\u0004\u0004\u0001\u001c\u0002\u0004\u0006\u001c\u0001\u001b\u0002\u001c" +
                    "\u0001\u0004\u0002\u001b\u0005\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0006\u001c\u0002\u001b\u000a\u001c\u0002\u001b" +
                    "\u0004\u0004\u0020\u001b\u0001\u0004\u0017\u001b\u0002\u001c\u0006\u001b\u000a\u001c\u000b\u001b\u0001\u001c\u0001\u001b" +
                    "\u0001\u001c\u0001\u001b\u0001\u001c\u0004\u001b\u0002\u001c\u0008\u0004\u0001\u001b\u0024\u0004\u0004\u001b\u0014\u001c" +
                    "\u0001\u001b\u0002\u001c\u0005\u0004\u000b\u001c\u0001\u001b\u0024\u001c\u0009\u001b\u0001\u001c\u0039\u001b\u002b\u0004" +
                    "\u0014\u001c\u0001\u0004\u000a\u001c\u0006\u001b\u0006\u0004\u0004\u001c\u0004\u0004\u0003\u001c\u0001\u0004\u0003\u001c" +
                    "\u0002\u0004\u0007\u001c\u0003\u0004\u0004\u001c\u000d\u0004\u000c\u001c\u0001\u0004\u000f\u001c\u0002\u001b\u0026\u0004" +
                    "\u0001\u001b\u0001\u0004\u0005\u001b\u0001\u0004\u0002\u001b\u002b\u0004\u0001\u001b\u014d\u0004\u0001\u001b\u0004\u0004" +
                    "\u0002\u001b\u0007\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0004\u0004\u0002\u001b\u0029\u0004\u0001\u001b\u0004\u0004" +
                    "\u0002\u001b\u0021\u0004\u0001\u001b\u0004\u0004\u0002\u001b\u0007\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0004\u0004" +
                    "\u0002\u001b\u000f\u0004\u0001\u001b\u0039\u0004\u0001\u001b\u0004\u0004\u0002\u001b\u0043\u0004\u0002\u001b\u0003\u001c" +
                    "\u0020\u001b\u0010\u0004\u0010\u001b\u0055\u0004\u000c\u001b\u026c\u0004\u0002\u001b\u0011\u0004\u0001\u0000\u001a\u0004" +
                    "\u0005\u001b\u004b\u0004\u0003\u001b\u0003\u0004\u000f\u001b\u000d\u0004\u0001\u001b\u0004\u0004\u0003\u001c\u000b\u001b" +
                    "\u0012\u0004\u0003\u001c\u000b\u001b\u0012\u0004\u0002\u001c\u000c\u001b\u000d\u0004\u0001\u001b\u0003\u0004\u0001\u001b" +
                    "\u0002\u001c\u000c\u001b\u0034\u0004\u0020\u001c\u0003\u001b\u0001\u0004\u0003\u001b\u0002\u0004\u0001\u001c\u0002\u001b" +
                    "\u000a\u001c\u0021\u001b\u0003\u001c\u0002\u001b\u000a\u001c\u0006\u001b\u0058\u0004\u0008\u001b\u0029\u0004\u0001\u001c" +
                    "\u0001\u0004\u0005\u001b\u0046\u0004\u000a\u001b\u001d\u0004\u0003\u001b\u000c\u001c\u0004\u001b\u000c\u001c\u000a\u001b" +
                    "\u000a\u001c\u001e\u0004\u0002\u001b\u0005\u0004\u000b\u001b\u002c\u0004\u0004\u001b\u0011\u001c\u0007\u0004\u0002\u001c" +
                    "\u0006\u001b\u000a\u001c\u0026\u001b\u0017\u0004\u0005\u001c\u0004\u001b\u0035\u0004\u000a\u001c\u0001\u001b\u001d\u001c" +
                    "\u0002\u001b\u000b\u001c\u0006\u001b\u000a\u001c\u000d\u001b\u0001\u0004\u0058\u001b\u0005\u001c\u002f\u0004\u0011\u001c" +
                    "\u0007\u0004\u0004\u001b\u000a\u001c\u0011\u001b\u0009\u001c\u000c\u001b\u0003\u001c\u001e\u0004\u000d\u001c\u0002\u0004" +
                    "\u000a\u001c\u002c\u0004\u000e\u001c\u000c\u001b\u0024\u0004\u0014\u001c\u0008\u001b\u000a\u001c\u0003\u001b\u0003\u0004" +
                    "\u000a\u001c\u0024\u0004\u0052\u001b\u0003\u001c\u0001\u001b\u0015\u001c\u0004\u0004\u0001\u001c\u0004\u0004\u0003\u001c" +
                    "\u0002\u0004\u0009\u001b\u00c0\u0004\u0027\u001c\u0015\u001b\u0004\u001c\u0116\u0004\u0002\u001b\u0006\u0004\u0002\u001b" +
                    "\u0026\u0004\u0002\u001b\u0006\u0004\u0002\u001b\u0008\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0001\u001b" +
                    "\u0001\u0004\u0001\u001b\u001f\u0004\u0002\u001b\u0035\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0001\u0004\u0003\u001b" +
                    "\u0003\u0004\u0001\u001b\u0007\u0004\u0003\u001b\u0004\u0004\u0002\u001b\u0006\u0004\u0004\u001b\u000d\u0004\u0005\u001b" +
                    "\u0003\u0004\u0001\u001b\u0007\u0004\u0003\u001b\u000b\u0000\u0005\u001c\u0018\u001b\u0002\u0000\u0005\u001c\u0001\u0000" +
                    "\u000f\u001b\u0002\u0004\u0013\u001b\u0001\u0004\u000a\u001b\u0001\u0000\u0005\u001c\u0005\u001b\u0006\u001c\u0001\u001b" +
                    "\u0001\u0004\u000d\u001b\u0001\u0004\u0010\u001b\u000d\u0004\u0003\u001b\u001b\u0004\u0015\u001b\u000d\u001c\u0004\u001b" +
                    "\u0001\u001c\u0003\u001b\u000c\u001c\u0011\u001b\u0001\u0004\u0004\u001b\u0001\u0004\u0002\u001b\u000a\u0004\u0001\u001b" +
                    "\u0001\u0004\u0003\u001b\u0005\u0004\u0006\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0001\u001b" +
                    "\u0004\u0004\u0001\u001b\u000b\u0004\u0002\u001b\u0004\u0004\u0005\u001b\u0005\u0004\u0004\u001b\u0001\u0004\u0011\u001b" +
                    "\u0029\u0004\u0a77\u001b\u002f\u0004\u0001\u001b\u002f\u0004\u0001\u001b\u0085\u0004\u0006\u001b\u0004\u0004\u0003\u001c" +
                    "\u0002\u0004\u000c\u001b\u0026\u0004\u0001\u001b\u0001\u0004\u0005\u001b\u0001\u0004\u0002\u001b\u0038\u0004\u0007\u001b" +
                    "\u0001\u0004\u000f\u001b\u0001\u001c\u0017\u0004\u0009\u001b\u0007\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0007\u0004" +
                    "\u0001\u001b\u0007\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0007\u0004" +
                    "\u0001\u001b\u0020\u001c\u002f\u001b\u0001\u0004\u01d0\u001b\u0001\u0000\u0004\u001b\u0003\u0004\u0019\u001b\u0009\u0004" +
                    "\u0006\u001c\u0001\u001b\u0005\u0004\u0002\u001b\u0005\u0004\u0004\u001b\u0056\u0004\u0002\u001b\u0002\u001c\u0002\u001b" +
                    "\u0003\u0004\u0001\u001b\u005a\u0004\u0001\u001b\u0004\u0004\u0005\u001b\u0029\u0004\u0003\u001b\u005e\u0004\u0011\u001b" +
                    "\u001b\u0004\u0035\u001b\u0010\u0004\u0200\u001b\u19b6\u0004\u004a\u001b\u51cd\u0004\u0033\u001b\u048d\u0004\u0043\u001b" +
                    "\u002e\u0004\u0002\u001b\u010d\u0004\u0003\u001b\u0010\u0004\u000a\u001c\u0002\u0004\u0014\u001b\u002f\u0004\u0001\u001c" +
                    "\u0004\u001b\u000a\u001c\u0001\u001b\u0019\u0004\u0007\u001b\u0001\u001c\u0050\u0004\u0002\u001c\u0025\u001b\u0009\u0004" +
                    "\u0002\u001b\u0067\u0004\u0002\u001b\u0004\u0004\u0001\u001b\u0004\u0004\u000c\u001b\u000b\u0004\u004d\u001b\u000a\u0004" +
                    "\u0001\u001c\u0003\u0004\u0001\u001c\u0004\u0004\u0001\u001c\u0017\u0004\u0005\u001c\u0010\u001b\u0001\u0004\u0007\u001b" +
                    "\u0034\u0004\u000c\u001b\u0002\u001c\u0032\u0004\u0011\u001c\u000b\u001b\u000a\u001c\u0006\u001b\u0012\u001c\u0006\u0004" +
                    "\u0003\u001b\u0001\u0004\u0004\u001b\u000a\u001c\u001c\u0004\u0008\u001c\u0002\u001b\u0017\u0004\u000d\u001c\u000c\u001b" +
                    "\u001d\u0004\u0003\u001b\u0004\u001c\u002f\u0004\u000e\u001c\u000e\u001b\u0001\u0004\u000a\u001c\u0026\u001b\u0029\u0004" +
                    "\u000e\u001c\u0009\u001b\u0003\u0004\u0001\u001c\u0008\u0004\u0002\u001c\u0002\u001b\u000a\u001c\u0006\u001b\u0017\u0004" +
                    "\u0003\u001b\u0001\u0004\u0001\u001c\u0004\u001b\u0030\u0004\u0001\u001c\u0001\u0004\u0003\u001c\u0002\u0004\u0002\u001c" +
                    "\u0005\u0004\u0002\u001c\u0001\u0004\u0001\u001c\u0001\u0004\u0018\u001b\u0003\u0004\u0002\u001b\u000b\u0004\u0005\u001c" +
                    "\u0002\u001b\u0003\u0004\u0002\u001c\u000a\u001b\u0006\u0004\u0002\u001b\u0006\u0004\u0002\u001b\u0006\u0004\u0009\u001b" +
                    "\u0007\u0004\u0001\u001b\u0007\u0004\u0091\u001b\u0023\u0004\u0008\u001c\u0001\u001b\u0002\u001c\u0002\u001b\u000a\u001c" +
                    "\u0006\u001b\u2ba4\u0004\u000c\u001b\u0017\u0004\u0004\u001b\u0031\u0004\u2104\u001b\u016e\u0004\u0002\u001b\u006a\u0004" +
                    "\u0026\u001b\u0007\u0004\u000c\u001b\u0005\u0004\u0005\u001b\u0001\u0004\u0001\u001c\u000a\u0004\u0001\u001b\u000d\u0004" +
                    "\u0001\u001b\u0005\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u006c\u0004" +
                    "\u0021\u001b\u016b\u0004\u0012\u001b\u0040\u0004\u0002\u001b\u0036\u0004\u0028\u001b\u000d\u0004\u0003\u001b\u0010\u001c" +
                    "\u0010\u001b\u0007\u001c\u000c\u001b\u0002\u0004\u0018\u001b\u0003\u0004\u0019\u001b\u0001\u0004\u0006\u001b\u0005\u0004" +
                    "\u0001\u001b\u0087\u0004\u0002\u001b\u0001\u001c\u0004\u001b\u0001\u0004\u000b\u001b\u000a\u001c\u0007\u001b\u001a\u0004" +
                    "\u0004\u001b\u0001\u0004\u0001\u001b\u001a\u0004\u000b\u001b\u0059\u0004\u0003\u001b\u0006\u0004\u0002\u001b\u0006\u0004" +
                    "\u0002\u001b\u0006\u0004\u0002\u001b\u0003\u0004\u0003\u001b\u0002\u0004\u0003\u001b\u0002\u0004\u0012\u001b\u0003\u001c" +
                    "\u0004\u001b\u000c\u0004\u0001\u001b\u001a\u0004\u0001\u001b\u0013\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u000f\u0004" +
                    "\u0002\u001b\u000e\u0004\u0022\u001b\u007b\u0004\u0045\u001b\u0035\u0004\u0088\u001b\u0001\u001c\u0082\u001b\u001d\u0004" +
                    "\u0003\u001b\u0031\u0004\u002f\u001b\u001f\u0004\u0011\u001b\u001b\u0004\u0035\u001b\u001e\u0004\u0002\u001b\u0024\u0004" +
                    "\u0004\u001b\u0008\u0004\u0001\u001b\u0005\u0004\u002a\u001b\u009e\u0004\u0002\u001b\u000a\u001c\u0356\u001b\u0006\u0004" +
                    "\u0002\u001b\u0001\u0004\u0001\u001b\u002c\u0004\u0001\u001b\u0002\u0004\u0003\u001b\u0001\u0004\u0002\u001b\u0017\u0004" +
                    "\u00aa\u001b\u0016\u0004\u000a\u001b\u001a\u0004\u0046\u001b\u0038\u0004\u0006\u001b\u0002\u0004\u0040\u001b\u0001\u0004" +
                    "\u0003\u001c\u0001\u001b\u0002\u001c\u0005\u001b\u0004\u001c\u0004\u0004\u0001\u001b\u0003\u0004\u0001\u001b\u001b\u0004" +
                    "\u0004\u001b\u0003\u001c\u0004\u001b\u0001\u001c\u0020\u001b\u001d\u0004\u0083\u001b\u0036\u0004\u000a\u001b\u0016\u0004" +
                    "\u000a\u001b\u0013\u0004\u008d\u001b\u0049\u0004\u03b7\u001b\u0003\u001c\u0035\u0004\u000f\u001c\u001f\u001b\u000a\u001c" +
                    "\u0010\u001b\u0003\u001c\u002d\u0004\u000b\u001c\u0002\u001b\u0001\u001c\u0012\u001b\u0019\u0004\u0007\u001b\u000a\u001c" +
                    "\u0006\u001b\u0003\u001c\u0024\u0004\u000e\u001c\u0001\u001b\u000a\u001c\u0040\u001b\u0003\u001c\u0030\u0004\u000e\u001c" +
                    "\u0004\u0004\u000b\u001b\u000a\u001c\u04a6\u001b\u002b\u0004\u000d\u001c\u0008\u001b\u000a\u001c\u0936\u001b\u036f\u0004" +
                    "\u0091\u001b\u0063\u0004\u0b9d\u001b\u042f\u0004\u33d1\u001b\u0239\u0004\u04c7\u001b\u0045\u0004\u000b\u001b\u0001\u0004" +
                    "\u002e\u001c\u0010\u001b\u0004\u001c\u000d\u0004\u4060\u001b\u0002\u0004\u2163\u001b\u0005\u001c\u0003\u001b\u0016\u001c" +
                    "\u0002\u001b\u0007\u001c\u001e\u001b\u0004\u001c\u0094\u001b\u0003\u001c\u01bb\u001b\u0055\u0004\u0001\u001b\u0047\u0004" +
                    "\u0001\u001b\u0002\u0004\u0002\u001b\u0001\u0004\u0002\u001b\u0002\u0004\u0002\u001b\u0004\u0004\u0001\u001b\u000c\u0004" +
                    "\u0001\u001b\u0001\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0041\u0004\u0001\u001b\u0004\u0004\u0002\u001b\u0008\u0004" +
                    "\u0001\u001b\u0007\u0004\u0001\u001b\u001c\u0004\u0001\u001b\u0004\u0004\u0001\u001b\u0005\u0004\u0001\u001b\u0001\u0004" +
                    "\u0003\u001b\u0007\u0004\u0001\u001b\u0154\u0004\u0002\u001b\u0019\u0004\u0001\u001b\u0019\u0004\u0001\u001b\u001f\u0004" +
                    "\u0001\u001b\u0019\u0004\u0001\u001b\u001f\u0004\u0001\u001b\u0019\u0004\u0001\u001b\u001f\u0004\u0001\u001b\u0019\u0004" +
                    "\u0001\u001b\u001f\u0004\u0001\u001b\u0019\u0004\u0001\u001b\u0008\u0004\u0002\u001b\u0032\u001c\u1600\u001b\u0004\u0004" +
                    "\u0001\u001b\u001b\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u0001\u0004\u0002\u001b\u0001\u0004\u0001\u001b\u000a\u0004" +
                    "\u0001\u001b\u0004\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0006\u001b\u0001\u0004\u0004\u001b\u0001\u0004" +
                    "\u0001\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0003\u0004\u0001\u001b\u0002\u0004\u0001\u001b\u0001\u0004" +
                    "\u0002\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u0001\u0004" +
                    "\u0001\u001b\u0002\u0004\u0001\u001b\u0001\u0004\u0002\u001b\u0004\u0004\u0001\u001b\u0007\u0004\u0001\u001b\u0004\u0004" +
                    "\u0001\u001b\u0004\u0004\u0001\u001b\u0001\u0004\u0001\u001b\u000a\u0004\u0001\u001b\u0011\u0004\u0005\u001b\u0003\u0004" +
                    "\u0001\u001b\u0005\u0004\u0001\u001b\u0011\u0004\u1144\u001b\ua6d7\u0004\u0029\u001b\u1035\u0004\u000b\u001b\u00de\u0004" +
                    "\u3fe2\u001b\u021e\u0004\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\uffff\u001b\u05ee\u001b" +
                    "\u0001\u001c\u001e\u001b\u0060\u001c\u0080\u001b\u00f0\u001c\uffff\u001b\uffff\u001b\ufe12\u001b"

        /**
         * Translates characters to character classes
         */
        private val ZZ_CMAP: CharArray = zzUnpackCMap(ZZ_CMAP_PACKED)

        /**
         * Translates DFA states to action switch labels.
         */
        private val ZZ_ACTION: IntArray = zzUnpackAction()

        private val ZZ_ACTION_PACKED_0 =
            "\u0001\u0000\u0001\u0001\u0005\u0000\u0001\u0002\u0002\u0003\u0001\u0004\u0001\u0005\u0001\u0006" +
                    "\u0001\u0007\u0001\u0006\u0001\u0008\u0001\u0009\u0007\u0005\u0001\u000a\u0001\u000b\u0001\u000c" +
                    "\u0001\u000d\u0001\u0002\u0001\u000e\u0009\u0005\u0001\u000f\u0001\u0010\u0001\u0011\u0001\u0012" +
                    "\u0001\u0013\u0001\u0014\u0001\u0015\u0001\u0016\u0001\u0017\u0001\u0018\u0001\u0019\u0001\u001a" +
                    "\u0001\u001b\u0001\u001c\u0001\u001d\u0001\u001e\u0001\u001f\u0001\u0020\u0001\u0021\u0002\u0022" +
                    "\u0001\u0002\u0001\u0000\u0002\u0023\u0002\u0006\u0001\u0000\u0001\u0006\u0001\u0024\u0001\u0025" +
                    "\u0004\u0005\u0001\u0026\u0001\u0027\u0001\u0028\u0003\u0005\u0001\u0029\u0001\u002a\u0001\u0000" +
                    "\u0001\u002b\u0002\u0000\u000e\u0005\u0001\u002c\u0001\u002d\u0001\u002e\u0001\u002f\u0001\u0030" +
                    "\u0001\u0031\u0001\u0032\u0001\u0033\u0001\u0034\u0001\u0028\u0001\u0022\u0004\u0000\u0001\u0035" +
                    "\u0002\u0000\u0002\u0006\u0001\u0036\u0002\u0000\u0002\u0005\u0001\u0037\u0002\u0005\u0001\u0038" +
                    "\u0001\u0010\u0001\u0005\u0001\u0039\u0001\u003a\u0001\u0034\u0004\u0005\u0001\u003b\u0009\u0005" +
                    "\u0001\u0000\u0001\u0035\u0001\u003c\u0001\u0000\u0001\u0006\u0004\u0000\u0002\u0005\u0001\u003d" +
                    "\u0001\u003e\u000a\u0005\u0001\u003f\u0001\u0040\u0001\u0041\u0001\u0042\u0001\u0005\u0001\u0043" +
                    "\u0002\u0000\u0001\u0044\u0001\u0006\u0002\u0000\u0003\u0005\u0001\u0045\u0001\u0005\u0001\u0046" +
                    "\u0001\u0047\u0002\u0005\u0001\u0048\u0001\u0005\u0001\u0049\u0001\u0005\u0001\u004a\u0001\u0000" +
                    "\u0001\u0006\u0002\u0000\u0001\u004b\u0001\u004c\u0001\u004d\u0001\u0005\u0001\u004e\u0001\u004f" +
                    "\u0002\u0005\u0003\u0000\u0001\u0050\u0002\u0005\u0001\u0051\u0001\u0000\u0001\u0052\u0001\u0053" +
                    "\u0001\u0051\u0002\u0000\u0002\u0054"

        private fun zzUnpackAction(): IntArray {
            val result = IntArray(224)
            var offset = 0
            offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackAction(packed: String, offset: Int, result: IntArray): Int {
            var i = 0 /* index in packed string  */
            var j = offset /* index in unpacked array */
            val l = packed.length
            while (i < l) {
                var count = packed.get(i++).code
                val value = packed.get(i++).code
                do result[j++] = value while (--count > 0)
            }
            return j
        }


        /**
         * Translates a state to a row index in the transition table
         */
        private val ZZ_ROWMAP: IntArray = zzUnpackRowMap()

        private val ZZ_ROWMAP_PACKED_0 =
            "\u0000\u0000\u0000\u003e\u0000\u007c\u0000\u00ba\u0000\u00f8\u0000\u0136\u0000\u0174\u0000\u01b2" +
                    "\u0000\u01f0\u0000\u01b2\u0000\u022e\u0000\u026c\u0000\u02aa\u0000\u01b2\u0000\u02e8\u0000\u0326" +
                    "\u0000\u0364\u0000\u03a2\u0000\u03e0\u0000\u041e\u0000\u045c\u0000\u049a\u0000\u04d8\u0000\u0516" +
                    "\u0000\u0554\u0000\u0592\u0000\u01b2\u0000\u01b2\u0000\u05d0\u0000\u01b2\u0000\u060e\u0000\u064c" +
                    "\u0000\u068a\u0000\u06c8\u0000\u0706\u0000\u0744\u0000\u0782\u0000\u07c0\u0000\u07fe\u0000\u083c" +
                    "\u0000\u087a\u0000\u08b8\u0000\u08f6\u0000\u087a\u0000\u01b2\u0000\u01b2\u0000\u0934\u0000\u01b2" +
                    "\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u0972\u0000\u01b2\u0000\u09b0" +
                    "\u0000\u09ee\u0000\u01b2\u0000\u0a2c\u0000\u0a6a\u0000\u0aa8\u0000\u0ae6\u0000\u01b2\u0000\u0b24" +
                    "\u0000\u0b62\u0000\u0ba0\u0000\u0bde\u0000\u0c1c\u0000\u0c5a\u0000\u0c98\u0000\u0cd6\u0000\u0d14" +
                    "\u0000\u0d52\u0000\u0d90\u0000\u026c\u0000\u026c\u0000\u026c\u0000\u0dce\u0000\u0e0c\u0000\u0e4a" +
                    "\u0000\u026c\u0000\u01b2\u0000\u0554\u0000\u01b2\u0000\u0e88\u0000\u0ec6\u0000\u0f04\u0000\u0f42" +
                    "\u0000\u0f80\u0000\u0fbe\u0000\u0ffc\u0000\u103a\u0000\u1078\u0000\u10b6\u0000\u10f4\u0000\u1132" +
                    "\u0000\u1170\u0000\u11ae\u0000\u11ec\u0000\u122a\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u01b2" +
                    "\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u01b2\u0000\u1268" +
                    "\u0000\u12a6\u0000\u12e4\u0000\u0aa8\u0000\u1322\u0000\u1360\u0000\u0c1c\u0000\u139e\u0000\u13dc" +
                    "\u0000\u01b2\u0000\u141a\u0000\u1458\u0000\u1496\u0000\u14d4\u0000\u026c\u0000\u1512\u0000\u1550" +
                    "\u0000\u026c\u0000\u026c\u0000\u158e\u0000\u01b2\u0000\u01b2\u0000\u026c\u0000\u15cc\u0000\u160a" +
                    "\u0000\u1648\u0000\u1686\u0000\u026c\u0000\u16c4\u0000\u1702\u0000\u1740\u0000\u177e\u0000\u17bc" +
                    "\u0000\u17fa\u0000\u1838\u0000\u1876\u0000\u18b4\u0000\u18f2\u0000\u1930\u0000\u196e\u0000\u19ac" +
                    "\u0000\u19ea\u0000\u0b62\u0000\u1a28\u0000\u1a66\u0000\u1aa4\u0000\u1ae2\u0000\u1b20\u0000\u1b5e" +
                    "\u0000\u026c\u0000\u1b9c\u0000\u1bda\u0000\u1c18\u0000\u1c56\u0000\u1c94\u0000\u1cd2\u0000\u1d10" +
                    "\u0000\u1d4e\u0000\u1d8c\u0000\u1dca\u0000\u026c\u0000\u026c\u0000\u026c\u0000\u026c\u0000\u1e08" +
                    "\u0000\u18f2\u0000\u1e46\u0000\u1e84\u0000\u1ec2\u0000\u1f00\u0000\u1f3e\u0000\u1f7c\u0000\u1fba" +
                    "\u0000\u1ff8\u0000\u2036\u0000\u026c\u0000\u2074\u0000\u026c\u0000\u026c\u0000\u20b2\u0000\u20f0" +
                    "\u0000\u026c\u0000\u212e\u0000\u026c\u0000\u216c\u0000\u026c\u0000\u21aa\u0000\u21e8\u0000\u2226" +
                    "\u0000\u2264\u0000\u026c\u0000\u026c\u0000\u026c\u0000\u22a2\u0000\u026c\u0000\u026c\u0000\u22e0" +
                    "\u0000\u231e\u0000\u235c\u0000\u239a\u0000\u23d8\u0000\u026c\u0000\u2416\u0000\u2454\u0000\u2492" +
                    "\u0000\u24d0\u0000\u026c\u0000\u026c\u0000\u250e\u0000\u254c\u0000\u258a\u0000\u25c8\u0000\u2606"

        private fun zzUnpackRowMap(): IntArray {
            val result = IntArray(224)
            var offset = 0
            offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackRowMap(packed: String, offset: Int, result: IntArray): Int {
            var i = 0 /* index in packed string  */
            var j = offset /* index in unpacked array */
            val l = packed.length
            while (i < l) {
                val high = packed.get(i++).code shl 16
                result[j++] = high or packed.get(i++).code
            }
            return j
        }

        /**
         * The transition table of the DFA
         */
        private val ZZ_TRANS: IntArray = zzUnpackTrans()

        private val ZZ_TRANS_PACKED_0 =
            "\u0001\u0008\u0001\u0009\u0001\u000a\u0001\u000b\u0001\u000c\u0001\u0008\u0001\u000d\u0002\u000c" +
                    "\u0001\u000e\u0001\u000c\u0001\u000f\u0001\u000c\u0001\u0010\u0001\u0011\u0001\u0012\u0001\u0013" +
                    "\u0001\u0014\u0001\u0015\u0001\u0016\u0001\u0017\u0001\u0018\u0001\u0019\u0001\u001a\u0001\u001b" +
                    "\u0001\u001c\u0001\u001d\u0002\u0008\u0001\u001e\u0001\u001f\u0001\u0020\u0001\u000c\u0001\u0021" +
                    "\u0001\u0022\u0001\u0023\u0001\u0024\u0001\u0025\u0001\u0026\u0002\u000c\u0001\u0027\u0001\u0028" +
                    "\u0001\u0029\u0001\u002a\u0001\u002b\u0001\u002c\u0001\u002d\u0001\u002e\u0001\u002f\u0001\u0030" +
                    "\u0001\u0031\u0001\u0032\u0001\u0033\u0001\u0034\u0001\u0035\u0001\u0036\u0001\u0037\u0001\u0038" +
                    "\u0001\u0039\u0001\u000c\u0001\u003a\u0001\u0002\u0002\u0000\u003b\u0002\u0019\u0000\u0001\u003b" +
                    "\u0041\u0000\u0001\u003c\u0020\u0000\u0016\u0008\u0001\u003d\u0027\u0008\u000e\u0000\u0001\u003e" +
                    "\u002f\u0000\u000e\u003f\u0001\u0040\u002f\u003f\u0040\u0000\u0001\u000a\u003e\u0000\u0001\u000b" +
                    "\u003e\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0007\u0000\u0001\u000d\u0001\u0000\u0001\u0041" +
                    "\u0002\u0000\u0001\u000d\u0001\u0000\u0001\u0042\u0002\u0000\u0001\u0041\u0033\u0000\u0001\u000d" +
                    "\u0001\u0000\u0001\u0041\u0002\u0000\u0001\u000d\u0001\u0043\u0001\u0042\u0002\u0000\u0001\u0041" +
                    "\u0033\u0000\u0001\u0044\u0004\u0000\u0001\u0044\u0001\u0000\u0001\u0045\u003e\u0000\u0001\u0046" +
                    "\u0033\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u0047\u0005\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u0048\u0001\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u0003\u000c\u0001\u0049\u0008\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0004\u000c\u0001\u004a\u0002\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0005\u000c\u0001\u004b\u0001\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0005\u000c" +
                    "\u0001\u004c\u0006\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0001\u004d\u0006\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0003\u000c\u0001\u004e" +
                    "\u0001\u004f\u0002\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u0050\u0002\u000c" +
                    "\u0001\u0051\u0002\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c" +
                    "\u0017\u0000\u0001\u0052\u0001\u0053\u003d\u0000\u0001\u0054\u0034\u0000\u0001\u0055\u0008\u0000" +
                    "\u0001\u0056\u002a\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u0057" +
                    "\u0001\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u0058\u0006\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0004\u000c\u0001\u0059\u0002\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0001\u005a" +
                    "\u000b\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000b\u000c\u0001\u005b\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0004\u000c\u0001\u005c\u0002\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u0001\u005d\u0005\u000c\u0001\u005e\u0005\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u005f" +
                    "\u0001\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0004\u000c\u0001\u0060\u0002\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u0001\u0061\u000b\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u0062\u0006\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u000a\u000c\u0001\u0063\u0001\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000a\u000c\u0001\u0064" +
                    "\u0001\u000c\u0012\u0000\u0001\u000c\u002c\u0000\u0001\u0065\u0029\u0000\u0001\u0066\u003d\u0000" +
                    "\u0001\u0067\u0014\u0000\u0001\u0068\u0028\u0000\u0001\u0069\u0015\u0000\u0001\u006a\u0041\u0000" +
                    "\u0001\u006b\u0044\u0000\u0001\u006c\u003f\u0000\u0001\u006d\u003e\u0000\u0001\u006e\u0002\u0000" +
                    "\u0019\u003b\u0001\u006f\u0001\u0070\u0023\u003b\u001a\u003c\u0001\u0071\u0002\u003c\u0001\u006f" +
                    "\u0020\u003c\u0016\u0000\u0001\u0072\u0001\u0073\u0034\u0000\u0001\u0074\u003d\u0000\u0001\u0075" +
                    "\u0035\u0000\u0001\u0044\u0002\u0000\u0001\u0076\u0001\u0000\u0001\u0044\u0002\u0000\u0001\u0076" +
                    "\u0035\u0000\u0001\u0077\u0004\u0000\u0001\u0077\u0038\u0000\u0003\u0078\u0002\u0000\u0001\u0078" +
                    "\u0004\u0000\u0001\u0078\u0004\u0000\u0001\u0078\u0008\u0000\u0002\u0078\u0003\u0000\u0001\u0078" +
                    "\u0001\u0000\u0001\u0078\u001e\u0000\u0001\u0044\u0004\u0000\u0001\u0044\u003f\u0000\u0001\u0079" +
                    "\u003f\u0000\u0001\u007a\u0001\u007b\u0031\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0008\u000c\u0001\u007c\u0001\u007d\u0002\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0006\u000c" +
                    "\u0001\u007e\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u0004\u000c\u0001\u007f\u0007\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0008\u000c\u0001\u0080" +
                    "\u0003\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0003\u000c\u0001\u0081\u0008\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u0008\u000c\u0001\u0082\u0003\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u0005\u000c\u0001\u0083\u0006\u000c\u0012\u0000\u0001\u000c\u002d\u0000\u0001\u0084\u003d\u0000" +
                    "\u0001\u0085\u0015\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0006\u000c\u0001\u0086" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u0087\u0005\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0007\u000c\u0001\u0088\u0004\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u0089\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0003\u000c\u0001\u008a\u0003\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0001\u008b\u0006\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u0003\u000c\u0001\u008c\u0008\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u008d\u0001\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0008\u000c\u0001\u008e" +
                    "\u0003\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0005\u000c\u0001\u008f\u0001\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u0004\u000c\u0001\u0090\u0007\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u0006\u000c\u0001\u0091\u0005\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u0092\u0005\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0001\u000c\u0001\u0093\u0001\u000c\u0001\u0094\u0003\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u000c\u000c\u0012\u0000\u0001\u000c\u0002\u0000\u0002\u003b\u0001\u0000\u0001\u003b\u0001\u0000" +
                    "\u0038\u003b\u0001\u0000\u0002\u003c\u0001\u0000\u0001\u003c\u0001\u0000\u0038\u003c\u0018\u0072" +
                    "\u0001\u0095\u0025\u0072\u0001\u0096\u0002\u0000\u000b\u0096\u0001\u0097\u002f\u0096\u0016\u0000" +
                    "\u0001\u0098\u002d\u0000\u0001\u0077\u0001\u0000\u0001\u0041\u0002\u0000\u0001\u0077\u0004\u0000" +
                    "\u0001\u0041\u0033\u0000\u0002\u0078\u0001\u0099\u0001\u0000\u0001\u009a\u0001\u0078\u0001\u0000" +
                    "\u0001\u009b\u0002\u0000\u0001\u0099\u0004\u0000\u0001\u0078\u0008\u0000\u0002\u0078\u0003\u0000" +
                    "\u0001\u0078\u0001\u0000\u0001\u0078\u0001\u0000\u0001\u009a\u0026\u0000\u0001\u009c\u0041\u0000" +
                    "\u0001\u009d\u002d\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u0006\u000c\u0001\u009e\u0005\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u009f\u0005\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u00a0\u0005\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0004\u000c\u0001\u00a1\u0002\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u00a2" +
                    "\u0005\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0001\u00a3\u000b\u000c\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u0001\u00a4\u000b\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0001\u00a5\u000b\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u0001\u000c\u0001\u00a6\u000a\u000c\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u0008\u000c\u0001\u00a7\u0003\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0004\u000c" +
                    "\u0001\u00a8\u0007\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0007\u000c\u0001\u00a9\u0004\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0003\u000c" +
                    "\u0001\u00aa\u0003\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u0008\u000c\u0001\u00ab\u0003\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u00ac\u0005\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0001\u000c\u0001\u00ad\u0005\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c" +
                    "\u0001\u00ae\u0001\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u00af\u0001\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0003\u000c" +
                    "\u0001\u00b0\u0008\u000c\u0012\u0000\u0001\u000c\u0001\u0000\u0017\u0072\u0001\u0095\u0001\u00b1" +
                    "\u0025\u0072\u0001\u0096\u0002\u0000\u003b\u0096\u0001\u0097\u0001\u00b2\u0001\u00b3\u003b\u0097" +
                    "\u0016\u0000\u0001\u00b4\u0001\u0098\u002c\u0000\u0002\u0078\u0001\u0099\u0001\u0076\u0001\u009a" +
                    "\u0001\u0078\u0001\u0000\u0001\u009b\u0001\u0076\u0001\u0000\u0001\u0099\u0004\u0000\u0001\u0078" +
                    "\u0008\u0000\u0002\u0078\u0003\u0000\u0001\u0078\u0001\u0000\u0001\u0078\u0001\u0000\u0001\u009a" +
                    "\u001c\u0000\u0003\u00b5\u0002\u0000\u0001\u00b5\u0004\u0000\u0001\u00b5\u0004\u0000\u0001\u00b5" +
                    "\u0008\u0000\u0002\u00b5\u0003\u0000\u0001\u00b5\u0001\u0000\u0001\u00b5\u0029\u0000\u0001\u00b6" +
                    "\u0041\u0000\u0001\u00b7\u002c\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u00b8" +
                    "\u0006\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u0001\u00b9\u000b\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0003\u000c\u0001\u00ba\u0003\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u00bb" +
                    "\u0006\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000" +
                    "\u0006\u000c\u0001\u00bc\u0005\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0002\u000c\u0001\u00bd" +
                    "\u0009\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0003\u000c\u0001\u00be\u0008\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0006\u000c\u0001\u00bf" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0007\u000c" +
                    "\u0001\u00c0\u0004\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0001\u000c\u0001\u00c1\u0005\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u0008\u000c\u0001\u00c2\u0003\u000c\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u0003\u000c\u0001\u00c3\u0008\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0003\u000c\u0001\u00c4\u0003\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0001\u000c\u0001\u00c5\u0005\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c" +
                    "\u0012\u0000\u0001\u000c\u0003\u0000\u0001\u00b3\u003e\u0000\u0001\u00b3\u000a\u0000\u0001\u00c6" +
                    "\u002f\u0000\u003e\u00b4\u0006\u0000\u0002\u00b5\u0001\u00c7\u0001\u0000\u0001\u009a\u0001\u00b5" +
                    "\u0004\u0000\u0001\u00c7\u0004\u0000\u0001\u00b5\u0008\u0000\u0002\u00b5\u0003\u0000\u0001\u00b5" +
                    "\u0001\u0000\u0001\u00b5\u0001\u0000\u0001\u009a\u0028\u0000\u0001\u00c8\u003a\u0000\u0001\u00c9" +
                    "\u0032\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u00ca\u0001\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c" +
                    "\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0008\u000c" +
                    "\u0001\u00cb\u0003\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c" +
                    "\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0005\u000c\u0001\u00cc\u0006\u000c" +
                    "\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c" +
                    "\u0006\u0000\u0001\u000c\u0001\u0000\u0003\u000c\u0001\u00cd\u0008\u000c\u0012\u0000\u0001\u000c" +
                    "\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c" +
                    "\u0001\u0000\u0001\u00ce\u000b\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000a\u000c\u0001\u00cf" +
                    "\u0001\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000" +
                    "\u0003\u000c\u0001\u00d0\u0003\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000" +
                    "\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u00d1" +
                    "\u0001\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u000f\u0000" +
                    "\u0001\u00d2\u0035\u0000\u0002\u00b5\u0001\u00c7\u0001\u0076\u0001\u009a\u0001\u00b5\u0002\u0000" +
                    "\u0001\u0076\u0001\u0000\u0001\u00c7\u0004\u0000\u0001\u00b5\u0008\u0000\u0002\u00b5\u0003\u0000" +
                    "\u0001\u00b5\u0001\u0000\u0001\u00b5\u0001\u0000\u0001\u009a\u0029\u0000\u0001\u00d3\u003a\u0000" +
                    "\u0001\u00d4\u0031\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u0008\u000c\u0001\u00d5\u0003\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0004\u000c\u0001\u00d6\u0002\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000\u0005\u000c\u0001\u0000" +
                    "\u0003\u000c\u0002\u0000\u0007\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u0006\u000c\u0001\u00d7" +
                    "\u0005\u000c\u0012\u0000\u0001\u000c\u000f\u0000\u0001\u0097\u0043\u0000\u0001\u00d8\u003a\u0000" +
                    "\u0001\u00d9\u0030\u0000\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0005\u000c\u0001\u00da" +
                    "\u0001\u000c\u0006\u0000\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0005\u0000" +
                    "\u0005\u000c\u0001\u0000\u0003\u000c\u0002\u0000\u0001\u000c\u0001\u00db\u0005\u000c\u0006\u0000" +
                    "\u0001\u000c\u0001\u0000\u000c\u000c\u0012\u0000\u0001\u000c\u0004\u0000\u0001\u00dc\u004c\u0000" +
                    "\u0001\u00dd\u002b\u0000\u0001\u00dc\u0002\u0000\u003b\u00dc\u0013\u0000\u0001\u00de\u003e\u0000" +
                    "\u0001\u00df\u002c\u0000\u0001\u00e0\u003a\u0000\u0001\u00e0\u0002\u0000\u003b\u00e0"

        private fun zzUnpackTrans(): IntArray {
            val result = IntArray(9796)
            var offset = 0
            offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackTrans(packed: String, offset: Int, result: IntArray): Int {
            var i = 0 /* index in packed string  */
            var j = offset /* index in unpacked array */
            val l = packed.length
            while (i < l) {
                var count = packed.get(i++).code
                var value = packed.get(i++).code
                value--
                do result[j++] = value while (--count > 0)
            }
            return j
        }


        /* error codes */
        private const val ZZ_UNKNOWN_ERROR = 0
        private const val ZZ_NO_MATCH = 1
        private const val ZZ_PUSHBACK_2BIG = 2

        /* error messages for the codes above */
        private val ZZ_ERROR_MSG = arrayOf<String?>(
            "Unknown internal scanner error",
            "Error: could not match input",
            "Error: pushback value was too large"
        )

        /**
         * ZZ_ATTRIBUTE[aState] contains the attributes of state `aState`
         */
        private val ZZ_ATTRIBUTE: IntArray = zzUnpackAttribute()

        private val ZZ_ATTRIBUTE_PACKED_0 =
            "\u0001\u0000\u0001\u0001\u0005\u0000\u0001\u0009\u0001\u0001\u0001\u0009\u0003\u0001\u0001\u0009" +
                    "\u000c\u0001\u0002\u0009\u0001\u0001\u0001\u0009\u000e\u0001\u0002\u0009\u0001\u0001\u0006\u0009" +
                    "\u0001\u0001\u0001\u0009\u0002\u0001\u0001\u0009\u0003\u0001\u0001\u0000\u0001\u0009\u0003\u0001" +
                    "\u0001\u0000\u000e\u0001\u0001\u0009\u0001\u0000\u0001\u0009\u0002\u0000\u000e\u0001\u000b\u0009" +
                    "\u0004\u0000\u0001\u0001\u0002\u0000\u0002\u0001\u0001\u0009\u0002\u0000\u0008\u0001\u0002\u0009" +
                    "\u000f\u0001\u0001\u0000\u0002\u0001\u0001\u0000\u0001\u0001\u0004\u0000\u0014\u0001\u0002\u0000" +
                    "\u0002\u0001\u0002\u0000\u000e\u0001\u0001\u0000\u0001\u0001\u0002\u0000\u0008\u0001\u0003\u0000" +
                    "\u0004\u0001\u0001\u0000\u0003\u0001\u0002\u0000\u0002\u0001"

        private fun zzUnpackAttribute(): IntArray {
            val result = IntArray(224)
            var offset = 0
            offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result)
            return result
        }

        private fun zzUnpackAttribute(packed: String, offset: Int, result: IntArray): Int {
            var i = 0 /* index in packed string  */
            var j = offset /* index in unpacked array */
            val l = packed.length
            while (i < l) {
                var count = packed.get(i++).code
                val value = packed.get(i++).code
                do result[j++] = value while (--count > 0)
            }
            return j
        }

        /**
         * Unpacks the compressed character translation table.
         *
         * @param packed the packed character translation table
         * @return the unpacked character translation table
         */
        private fun zzUnpackCMap(packed: String): CharArray {
            val map = CharArray(0x110000)
            var i = 0 /* index in packed string  */
            var j = 0 /* index in unpacked array */
            while (i < 2884) {
                var count = packed.get(i++).code
                val value = packed.get(i++)
                do map[j++] = value while (--count > 0)
            }
            return map
        }
    }
}
