package com.luaforge.studio.lxclua.utils

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.vector.ImageVector

/**
 * Material图标名称到ImageVector的映射
 * 用于分类图标选择功能
 */
val MATERIAL_ICON_MAP: Map<String, ImageVector> = mapOf(
    "Folder" to Icons.Filled.Folder,
    "Code" to Icons.Filled.Code,
    "Gamepad" to Icons.Filled.Gamepad,
    "MusicNote" to Icons.Filled.MusicNote,
    "Movie" to Icons.Filled.Movie,
    "Book" to Icons.Filled.Book,
    "Work" to Icons.Filled.Work,
    "School" to Icons.Filled.School,
    "Home" to Icons.Filled.Home,
    "Star" to Icons.Filled.Star,
    "Favorite" to Icons.Filled.Favorite,
    "Build" to Icons.Filled.Build,
    "Settings" to Icons.Filled.Settings,
    "Phone" to Icons.Filled.Phone,
    "Email" to Icons.Filled.Email,
    "Chat" to Icons.Filled.Chat,
    "Camera" to Icons.Filled.Camera,
    "Photo" to Icons.Filled.Photo,
    "Map" to Icons.Filled.Map,
    "Store" to Icons.Filled.Store,
    "FitnessCenter" to Icons.Filled.FitnessCenter,
    "LocalCafe" to Icons.Filled.LocalCafe,
    "Restaurant" to Icons.Filled.Restaurant,
    "Flight" to Icons.Filled.Flight,
    "Hotel" to Icons.Filled.Hotel,
    "DirectionsCar" to Icons.Filled.DirectionsCar,
    "Pets" to Icons.Filled.Pets,
    "Nature" to Icons.Filled.Nature,
    "Science" to Icons.Filled.Science,
    "Security" to Icons.Filled.Security,
    "Android" to Icons.Filled.Android,
    "Apps" to Icons.Filled.Apps,
    "Brush" to Icons.Filled.Brush,
    "BugReport" to Icons.Filled.BugReport,
    "Calculate" to Icons.Filled.Calculate,
    "Cloud" to Icons.Filled.Cloud,
    "ColorLens" to Icons.Filled.ColorLens,
    "Create" to Icons.Filled.Create,
    "Dashboard" to Icons.Filled.Dashboard,
    "Description" to Icons.Filled.Description,
    "Extension" to Icons.Filled.Extension,
    "Face" to Icons.Filled.Face,
    "Games" to Icons.Filled.Games,
    "GraphicEq" to Icons.Filled.GraphicEq,
    "Headset" to Icons.Filled.Headset,
    "Help" to Icons.Filled.Help,
    "Image" to Icons.Filled.Image,
    "Keyboard" to Icons.Filled.Keyboard,
    "Label" to Icons.Filled.Label,
    "Language" to Icons.Filled.Language,
    "Layers" to Icons.Filled.Layers,
    "Lightbulb" to Icons.Filled.Lightbulb,
    "Link" to Icons.Filled.Link,
    "List" to Icons.Filled.List,
    "Lock" to Icons.Filled.Lock,
    "Memory" to Icons.Filled.Memory,
    "MenuBook" to Icons.Filled.MenuBook,
    "Mouse" to Icons.Filled.Mouse,
    "Palette" to Icons.Filled.Palette,
    "Person" to Icons.Filled.Person,
    "PhoneAndroid" to Icons.Filled.PhoneAndroid,
    "PlayArrow" to Icons.Filled.PlayArrow,
    "Public" to Icons.Filled.Public,
    "PushPin" to Icons.Filled.PushPin,
    "Quiz" to Icons.Filled.Quiz,
    "RecordVoiceOver" to Icons.Filled.RecordVoiceOver,
    "RocketLaunch" to Icons.Filled.RocketLaunch,
    "Router" to Icons.Filled.Router,
    "Save" to Icons.Filled.Save,
    "Search" to Icons.Filled.Search,
    "SecurityUpdateGood" to Icons.Filled.SecurityUpdateGood,
    "Share" to Icons.Filled.Share,
    "ShoppingBag" to Icons.Filled.ShoppingBag,
    "Smartphone" to Icons.Filled.Smartphone,
    "Speed" to Icons.Filled.Speed,
    "SportsEsports" to Icons.Filled.SportsEsports,
    "Storage" to Icons.Filled.Storage,
    "Terminal" to Icons.Filled.Terminal,
    "TextFields" to Icons.Filled.TextFields,
    "ThumbUp" to Icons.Filled.ThumbUp,
    "Timer" to Icons.Filled.Timer,
    "Toc" to Icons.Filled.Toc,
    "ToggleOn" to Icons.Filled.ToggleOn,
    "Toll" to Icons.Filled.Toll,
    "TouchApp" to Icons.Filled.TouchApp,
    "Translate" to Icons.Filled.Translate,
    "Troubleshoot" to Icons.Filled.Troubleshoot,
    "Verified" to Icons.Filled.Verified,
    "VideogameAsset" to Icons.Filled.VideogameAsset,
    "Visibility" to Icons.Filled.Visibility,
    "Wallpaper" to Icons.Filled.Wallpaper,
    "Warning" to Icons.Filled.Warning,
    "Widgets" to Icons.Filled.Widgets,
    "Wifi" to Icons.Filled.Wifi,
)

/**
 * 根据名称获取图标
 */
fun getIconByName(name: String): ImageVector? {
    return MATERIAL_ICON_MAP[name]
}
